# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filenametemplatesinfo.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogFilenameTemplatesInfo(object):
    def setupUi(self, DialogFilenameTemplatesInfo):
        DialogFilenameTemplatesInfo.setObjectName("DialogFilenameTemplatesInfo")
        DialogFilenameTemplatesInfo.resize(400, 317)
        DialogFilenameTemplatesInfo.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(DialogFilenameTemplatesInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(DialogFilenameTemplatesInfo)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_13)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_11)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_10)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(299, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_15 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.PlainText)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_16)
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setTextFormat(QtCore.Qt.PlainText)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogFilenameTemplatesInfo)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(DialogFilenameTemplatesInfo)
        self.buttonBox.accepted.connect(DialogFilenameTemplatesInfo.accept)
        self.buttonBox.rejected.connect(DialogFilenameTemplatesInfo.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogFilenameTemplatesInfo)

    def retranslateUi(self, DialogFilenameTemplatesInfo):
        _translate = QtCore.QCoreApplication.translate
        DialogFilenameTemplatesInfo.setWindowTitle(_translate("DialogFilenameTemplatesInfo", "Filename Substitution Keys"))
        self.label.setText(_translate("DialogFilenameTemplatesInfo", "Key"))
        self.label_2.setText(_translate("DialogFilenameTemplatesInfo", "Description"))
        self.label_3.setText(_translate("DialogFilenameTemplatesInfo", "<title>"))
        self.label_4.setText(_translate("DialogFilenameTemplatesInfo", "Replaced by the disc title."))
        self.label_5.setText(_translate("DialogFilenameTemplatesInfo", "<preset>"))
        self.label_14.setText(_translate("DialogFilenameTemplatesInfo", "Replaced by the tag for the selected preset."))
        self.label_8.setText(_translate("DialogFilenameTemplatesInfo", "<acodec>"))
        self.label_13.setText(_translate("DialogFilenameTemplatesInfo", "Replaced by the tag for the selected audio mixdown."))
        self.label_9.setText(_translate("DialogFilenameTemplatesInfo", "<epno>"))
        self.label_12.setText(_translate("DialogFilenameTemplatesInfo", "Replaced by the episode number."))
        self.label_6.setText(_translate("DialogFilenameTemplatesInfo", "<eptitle>"))
        self.label_11.setText(_translate("DialogFilenameTemplatesInfo", "Replaced by the title track name."))
        self.label_7.setText(_translate("DialogFilenameTemplatesInfo", "<cetitle>"))
        self.label_10.setText(_translate("DialogFilenameTemplatesInfo", "Replaced by the chapter episode title."))
        self.label_15.setText(_translate("DialogFilenameTemplatesInfo", "Flag"))
        self.label_16.setText(_translate("DialogFilenameTemplatesInfo", "Description"))
        self.label_18.setText(_translate("DialogFilenameTemplatesInfo", "<$_>"))
        self.label_17.setText(_translate("DialogFilenameTemplatesInfo", "Replace all spaces in the filename with underscores."))

