# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 720)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Disc = QtWidgets.QWidget()
        self.tab_Disc.setObjectName("tab_Disc")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_Disc)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_Disc_Source = QtWidgets.QFrame(self.tab_Disc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Disc_Source.sizePolicy().hasHeightForWidth())
        self.frame_Disc_Source.setSizePolicy(sizePolicy)
        self.frame_Disc_Source.setMaximumSize(QtCore.QSize(16777215, 56))
        self.frame_Disc_Source.setStyleSheet("")
        self.frame_Disc_Source.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Disc_Source.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Disc_Source.setObjectName("frame_Disc_Source")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_Disc_Source)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_Disc_Source = QtWidgets.QLabel(self.frame_Disc_Source)
        self.label_Disc_Source.setObjectName("label_Disc_Source")
        self.gridLayout_5.addWidget(self.label_Disc_Source, 0, 0, 1, 1)
        self.lineEdit_Disc_Source = QtWidgets.QLineEdit(self.frame_Disc_Source)
        self.lineEdit_Disc_Source.setObjectName("lineEdit_Disc_Source")
        self.gridLayout_5.addWidget(self.lineEdit_Disc_Source, 0, 1, 1, 1)
        self.pushButton_Disc_Source_Browse = QtWidgets.QPushButton(self.frame_Disc_Source)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Disc_Source_Browse.sizePolicy().hasHeightForWidth())
        self.pushButton_Disc_Source_Browse.setSizePolicy(sizePolicy)
        self.pushButton_Disc_Source_Browse.setObjectName("pushButton_Disc_Source_Browse")
        self.gridLayout_5.addWidget(self.pushButton_Disc_Source_Browse, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 7, 1, 1)
        self.toolButton_Disc_RunVLC = QtWidgets.QToolButton(self.frame_Disc_Source)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/vlc_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_Disc_RunVLC.setIcon(icon)
        self.toolButton_Disc_RunVLC.setObjectName("toolButton_Disc_RunVLC")
        self.gridLayout_5.addWidget(self.toolButton_Disc_RunVLC, 0, 6, 1, 1)
        self.toolButton_Disc_Source_Read = QtWidgets.QToolButton(self.frame_Disc_Source)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/refresh_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_Disc_Source_Read.setIcon(icon1)
        self.toolButton_Disc_Source_Read.setObjectName("toolButton_Disc_Source_Read")
        self.gridLayout_5.addWidget(self.toolButton_Disc_Source_Read, 0, 3, 1, 1)
        self.toolButton_Disc_Source_Find = QtWidgets.QToolButton(self.frame_Disc_Source)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/magnifier_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_Disc_Source_Find.setIcon(icon2)
        self.toolButton_Disc_Source_Find.setObjectName("toolButton_Disc_Source_Find")
        self.gridLayout_5.addWidget(self.toolButton_Disc_Source_Find, 0, 4, 1, 1)
        self.toolButton_Disc_UpdateHash = QtWidgets.QToolButton(self.frame_Disc_Source)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/hash_blue_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_Disc_UpdateHash.setIcon(icon3)
        self.toolButton_Disc_UpdateHash.setObjectName("toolButton_Disc_UpdateHash")
        self.gridLayout_5.addWidget(self.toolButton_Disc_UpdateHash, 0, 5, 1, 1)
        self.label_Disc_DiskLabel = QtWidgets.QLabel(self.frame_Disc_Source)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_DiskLabel.sizePolicy().hasHeightForWidth())
        self.label_Disc_DiskLabel.setSizePolicy(sizePolicy)
        self.label_Disc_DiskLabel.setObjectName("label_Disc_DiskLabel")
        self.gridLayout_5.addWidget(self.label_Disc_DiskLabel, 0, 8, 1, 1)
        self.lineEdit_Disc_DiskLabel = QtWidgets.QLineEdit(self.frame_Disc_Source)
        self.lineEdit_Disc_DiskLabel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Disc_DiskLabel.sizePolicy().hasHeightForWidth())
        self.lineEdit_Disc_DiskLabel.setSizePolicy(sizePolicy)
        self.lineEdit_Disc_DiskLabel.setAutoFillBackground(False)
        self.lineEdit_Disc_DiskLabel.setStyleSheet(":disabled { color: Black; }")
        self.lineEdit_Disc_DiskLabel.setReadOnly(True)
        self.lineEdit_Disc_DiskLabel.setObjectName("lineEdit_Disc_DiskLabel")
        self.gridLayout_5.addWidget(self.lineEdit_Disc_DiskLabel, 0, 9, 1, 1)
        self.toolButton_Disc_GetSourceDiskLabel = QtWidgets.QToolButton(self.frame_Disc_Source)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/drive_magnify_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_Disc_GetSourceDiskLabel.setIcon(icon4)
        self.toolButton_Disc_GetSourceDiskLabel.setObjectName("toolButton_Disc_GetSourceDiskLabel")
        self.gridLayout_5.addWidget(self.toolButton_Disc_GetSourceDiskLabel, 0, 10, 1, 1)
        self.toolButton_Disc_EditSourceDiskLabel = QtWidgets.QToolButton(self.frame_Disc_Source)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/drive_edit_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_Disc_EditSourceDiskLabel.setIcon(icon5)
        self.toolButton_Disc_EditSourceDiskLabel.setObjectName("toolButton_Disc_EditSourceDiskLabel")
        self.gridLayout_5.addWidget(self.toolButton_Disc_EditSourceDiskLabel, 0, 11, 1, 1)
        self.label_Disc_Destination = QtWidgets.QLabel(self.frame_Disc_Source)
        self.label_Disc_Destination.setObjectName("label_Disc_Destination")
        self.gridLayout_5.addWidget(self.label_Disc_Destination, 1, 0, 1, 1)
        self.lineEdit_Disc_Destination = QtWidgets.QLineEdit(self.frame_Disc_Source)
        self.lineEdit_Disc_Destination.setObjectName("lineEdit_Disc_Destination")
        self.gridLayout_5.addWidget(self.lineEdit_Disc_Destination, 1, 1, 1, 1)
        self.pushButton_Disc_Destination_Browse = QtWidgets.QPushButton(self.frame_Disc_Source)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Disc_Destination_Browse.sizePolicy().hasHeightForWidth())
        self.pushButton_Disc_Destination_Browse.setSizePolicy(sizePolicy)
        self.pushButton_Disc_Destination_Browse.setObjectName("pushButton_Disc_Destination_Browse")
        self.gridLayout_5.addWidget(self.pushButton_Disc_Destination_Browse, 1, 2, 1, 1)
        self.checkBox_Disc_NoDVDNAV = QtWidgets.QCheckBox(self.frame_Disc_Source)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Disc_NoDVDNAV.sizePolicy().hasHeightForWidth())
        self.checkBox_Disc_NoDVDNAV.setSizePolicy(sizePolicy)
        self.checkBox_Disc_NoDVDNAV.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_Disc_NoDVDNAV.setObjectName("checkBox_Disc_NoDVDNAV")
        self.gridLayout_5.addWidget(self.checkBox_Disc_NoDVDNAV, 1, 8, 1, 2)
        self.verticalLayout_2.addWidget(self.frame_Disc_Source)
        self.frame_2 = QtWidgets.QFrame(self.tab_Disc)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 104))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_Disc_FileName = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_Disc_FileName.setObjectName("groupBox_Disc_FileName")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_Disc_FileName)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Disc_Title = QtWidgets.QLabel(self.groupBox_Disc_FileName)
        self.label_Disc_Title.setObjectName("label_Disc_Title")
        self.gridLayout_2.addWidget(self.label_Disc_Title, 0, 0, 1, 1)
        self.lineEdit_Disc_Title = QtWidgets.QLineEdit(self.groupBox_Disc_FileName)
        self.lineEdit_Disc_Title.setClearButtonEnabled(True)
        self.lineEdit_Disc_Title.setObjectName("lineEdit_Disc_Title")
        self.gridLayout_2.addWidget(self.lineEdit_Disc_Title, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_Disc_FirstEpisode = QtWidgets.QLabel(self.groupBox_Disc_FileName)
        self.label_Disc_FirstEpisode.setObjectName("label_Disc_FirstEpisode")
        self.gridLayout_2.addWidget(self.label_Disc_FirstEpisode, 0, 3, 1, 1)
        self.spinBox_Disc_FirstEpisode = QtWidgets.QSpinBox(self.groupBox_Disc_FileName)
        self.spinBox_Disc_FirstEpisode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Disc_FirstEpisode.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_Disc_FirstEpisode.setProperty("value", 1)
        self.spinBox_Disc_FirstEpisode.setObjectName("spinBox_Disc_FirstEpisode")
        self.gridLayout_2.addWidget(self.spinBox_Disc_FirstEpisode, 0, 4, 1, 1)
        self.toolButton_ResetFirstEpisode = QtWidgets.QToolButton(self.groupBox_Disc_FileName)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/redo_2_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_ResetFirstEpisode.setIcon(icon6)
        self.toolButton_ResetFirstEpisode.setObjectName("toolButton_ResetFirstEpisode")
        self.gridLayout_2.addWidget(self.toolButton_ResetFirstEpisode, 0, 5, 1, 1)
        self.label_Disc_Mask = QtWidgets.QLabel(self.groupBox_Disc_FileName)
        self.label_Disc_Mask.setObjectName("label_Disc_Mask")
        self.gridLayout_2.addWidget(self.label_Disc_Mask, 1, 0, 1, 1)
        self.comboBox_Disc_Mask = QtWidgets.QComboBox(self.groupBox_Disc_FileName)
        self.comboBox_Disc_Mask.setObjectName("comboBox_Disc_Mask")
        self.gridLayout_2.addWidget(self.comboBox_Disc_Mask, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.label_Disc_EpisodeNumberPrecision = QtWidgets.QLabel(self.groupBox_Disc_FileName)
        self.label_Disc_EpisodeNumberPrecision.setObjectName("label_Disc_EpisodeNumberPrecision")
        self.gridLayout_2.addWidget(self.label_Disc_EpisodeNumberPrecision, 1, 3, 1, 1)
        self.spinBox_Disc_EpisodeNumberPrecision = QtWidgets.QSpinBox(self.groupBox_Disc_FileName)
        self.spinBox_Disc_EpisodeNumberPrecision.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_Disc_EpisodeNumberPrecision.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Disc_EpisodeNumberPrecision.setProperty("value", 2)
        self.spinBox_Disc_EpisodeNumberPrecision.setObjectName("spinBox_Disc_EpisodeNumberPrecision")
        self.gridLayout_2.addWidget(self.spinBox_Disc_EpisodeNumberPrecision, 1, 4, 1, 1)
        self.toolButton_ResetEpisodeNumberPrecision = QtWidgets.QToolButton(self.groupBox_Disc_FileName)
        self.toolButton_ResetEpisodeNumberPrecision.setIcon(icon6)
        self.toolButton_ResetEpisodeNumberPrecision.setObjectName("toolButton_ResetEpisodeNumberPrecision")
        self.gridLayout_2.addWidget(self.toolButton_ResetEpisodeNumberPrecision, 1, 5, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_Disc_FileName)
        self.groupBox_Disc_Notes = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Disc_Notes.sizePolicy().hasHeightForWidth())
        self.groupBox_Disc_Notes.setSizePolicy(sizePolicy)
        self.groupBox_Disc_Notes.setObjectName("groupBox_Disc_Notes")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Disc_Notes)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit_Disc_Notes = QtWidgets.QPlainTextEdit(self.groupBox_Disc_Notes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_Disc_Notes.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_Disc_Notes.setSizePolicy(sizePolicy)
        self.plainTextEdit_Disc_Notes.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit_Disc_Notes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEdit_Disc_Notes.setTabChangesFocus(True)
        self.plainTextEdit_Disc_Notes.setBackgroundVisible(False)
        self.plainTextEdit_Disc_Notes.setObjectName("plainTextEdit_Disc_Notes")
        self.verticalLayout.addWidget(self.plainTextEdit_Disc_Notes)
        self.horizontalLayout_10.addWidget(self.groupBox_Disc_Notes)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.tab_Disc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 162))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 162))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_Processing = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Processing.sizePolicy().hasHeightForWidth())
        self.groupBox_Processing.setSizePolicy(sizePolicy)
        self.groupBox_Processing.setMinimumSize(QtCore.QSize(270, 161))
        self.groupBox_Processing.setMaximumSize(QtCore.QSize(270, 16777215))
        self.groupBox_Processing.setObjectName("groupBox_Processing")
        self.label_Disc_Preset = QtWidgets.QLabel(self.groupBox_Processing)
        self.label_Disc_Preset.setGeometry(QtCore.QRect(12, 35, 37, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_Preset.sizePolicy().hasHeightForWidth())
        self.label_Disc_Preset.setSizePolicy(sizePolicy)
        self.label_Disc_Preset.setObjectName("label_Disc_Preset")
        self.comboBox_Disc_Preset = QtWidgets.QComboBox(self.groupBox_Processing)
        self.comboBox_Disc_Preset.setGeometry(QtCore.QRect(57, 32, 201, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Disc_Preset.sizePolicy().hasHeightForWidth())
        self.comboBox_Disc_Preset.setSizePolicy(sizePolicy)
        self.comboBox_Disc_Preset.setMinimumSize(QtCore.QSize(201, 0))
        self.comboBox_Disc_Preset.setMaximumSize(QtCore.QSize(201, 16777215))
        self.comboBox_Disc_Preset.setObjectName("comboBox_Disc_Preset")
        self.horizontalLayout.addWidget(self.groupBox_Processing)
        self.groupBox_Disc_AudioTracks = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Disc_AudioTracks.sizePolicy().hasHeightForWidth())
        self.groupBox_Disc_AudioTracks.setSizePolicy(sizePolicy)
        self.groupBox_Disc_AudioTracks.setMinimumSize(QtCore.QSize(0, 161))
        self.groupBox_Disc_AudioTracks.setObjectName("groupBox_Disc_AudioTracks")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_Disc_AudioTracks)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.toolButton_Disc_Find_AudioTracks = QtWidgets.QToolButton(self.groupBox_Disc_AudioTracks)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/find_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Disc_Find_AudioTracks.setIcon(icon7)
        self.toolButton_Disc_Find_AudioTracks.setObjectName("toolButton_Disc_Find_AudioTracks")
        self.gridLayout_6.addWidget(self.toolButton_Disc_Find_AudioTracks, 0, 0, 1, 1)
        self.label_Disc_AudioTracks_Primary = QtWidgets.QLabel(self.groupBox_Disc_AudioTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_AudioTracks_Primary.sizePolicy().hasHeightForWidth())
        self.label_Disc_AudioTracks_Primary.setSizePolicy(sizePolicy)
        self.label_Disc_AudioTracks_Primary.setObjectName("label_Disc_AudioTracks_Primary")
        self.gridLayout_6.addWidget(self.label_Disc_AudioTracks_Primary, 0, 1, 1, 1)
        self.comboBox_Disc_AudioTracks_Mixdown_First_Primary = QtWidgets.QComboBox(self.groupBox_Disc_AudioTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Disc_AudioTracks_Mixdown_First_Primary.sizePolicy().hasHeightForWidth())
        self.comboBox_Disc_AudioTracks_Mixdown_First_Primary.setSizePolicy(sizePolicy)
        self.comboBox_Disc_AudioTracks_Mixdown_First_Primary.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_Disc_AudioTracks_Mixdown_First_Primary.setObjectName("comboBox_Disc_AudioTracks_Mixdown_First_Primary")
        self.gridLayout_6.addWidget(self.comboBox_Disc_AudioTracks_Mixdown_First_Primary, 1, 1, 1, 1)
        self.comboBox_Disc_AudioTracks_Mixdown_Second_Primary = QtWidgets.QComboBox(self.groupBox_Disc_AudioTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Disc_AudioTracks_Mixdown_Second_Primary.sizePolicy().hasHeightForWidth())
        self.comboBox_Disc_AudioTracks_Mixdown_Second_Primary.setSizePolicy(sizePolicy)
        self.comboBox_Disc_AudioTracks_Mixdown_Second_Primary.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_Disc_AudioTracks_Mixdown_Second_Primary.setObjectName("comboBox_Disc_AudioTracks_Mixdown_Second_Primary")
        self.gridLayout_6.addWidget(self.comboBox_Disc_AudioTracks_Mixdown_Second_Primary, 2, 1, 1, 1)
        self.comboBox_Disc_AudioTracks_SelectTrack_First = QtWidgets.QComboBox(self.groupBox_Disc_AudioTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Disc_AudioTracks_SelectTrack_First.sizePolicy().hasHeightForWidth())
        self.comboBox_Disc_AudioTracks_SelectTrack_First.setSizePolicy(sizePolicy)
        self.comboBox_Disc_AudioTracks_SelectTrack_First.setObjectName("comboBox_Disc_AudioTracks_SelectTrack_First")
        self.gridLayout_6.addWidget(self.comboBox_Disc_AudioTracks_SelectTrack_First, 1, 0, 1, 1)
        self.comboBox_Disc_AudioTracks_Mixdown_Third_Primary = QtWidgets.QComboBox(self.groupBox_Disc_AudioTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Disc_AudioTracks_Mixdown_Third_Primary.sizePolicy().hasHeightForWidth())
        self.comboBox_Disc_AudioTracks_Mixdown_Third_Primary.setSizePolicy(sizePolicy)
        self.comboBox_Disc_AudioTracks_Mixdown_Third_Primary.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_Disc_AudioTracks_Mixdown_Third_Primary.setObjectName("comboBox_Disc_AudioTracks_Mixdown_Third_Primary")
        self.gridLayout_6.addWidget(self.comboBox_Disc_AudioTracks_Mixdown_Third_Primary, 3, 1, 1, 1)
        self.comboBox_Disc_AudioTracks_Mixdown_Second_Secondary = QtWidgets.QComboBox(self.groupBox_Disc_AudioTracks)
        self.comboBox_Disc_AudioTracks_Mixdown_Second_Secondary.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_Disc_AudioTracks_Mixdown_Second_Secondary.setObjectName("comboBox_Disc_AudioTracks_Mixdown_Second_Secondary")
        self.gridLayout_6.addWidget(self.comboBox_Disc_AudioTracks_Mixdown_Second_Secondary, 2, 2, 1, 1)
        self.comboBox_Disc_AudioTracks_SelectTrack_Second = QtWidgets.QComboBox(self.groupBox_Disc_AudioTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Disc_AudioTracks_SelectTrack_Second.sizePolicy().hasHeightForWidth())
        self.comboBox_Disc_AudioTracks_SelectTrack_Second.setSizePolicy(sizePolicy)
        self.comboBox_Disc_AudioTracks_SelectTrack_Second.setObjectName("comboBox_Disc_AudioTracks_SelectTrack_Second")
        self.gridLayout_6.addWidget(self.comboBox_Disc_AudioTracks_SelectTrack_Second, 2, 0, 1, 1)
        self.comboBox_Disc_AudioTracks_Mixdown_Third_Secondary = QtWidgets.QComboBox(self.groupBox_Disc_AudioTracks)
        self.comboBox_Disc_AudioTracks_Mixdown_Third_Secondary.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_Disc_AudioTracks_Mixdown_Third_Secondary.setObjectName("comboBox_Disc_AudioTracks_Mixdown_Third_Secondary")
        self.gridLayout_6.addWidget(self.comboBox_Disc_AudioTracks_Mixdown_Third_Secondary, 3, 2, 1, 1)
        self.label_Disc_AudioTracks_Secondary = QtWidgets.QLabel(self.groupBox_Disc_AudioTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_AudioTracks_Secondary.sizePolicy().hasHeightForWidth())
        self.label_Disc_AudioTracks_Secondary.setSizePolicy(sizePolicy)
        self.label_Disc_AudioTracks_Secondary.setObjectName("label_Disc_AudioTracks_Secondary")
        self.gridLayout_6.addWidget(self.label_Disc_AudioTracks_Secondary, 0, 2, 1, 1)
        self.comboBox_Disc_AudioTracks_SelectTrack_Third = QtWidgets.QComboBox(self.groupBox_Disc_AudioTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Disc_AudioTracks_SelectTrack_Third.sizePolicy().hasHeightForWidth())
        self.comboBox_Disc_AudioTracks_SelectTrack_Third.setSizePolicy(sizePolicy)
        self.comboBox_Disc_AudioTracks_SelectTrack_Third.setObjectName("comboBox_Disc_AudioTracks_SelectTrack_Third")
        self.gridLayout_6.addWidget(self.comboBox_Disc_AudioTracks_SelectTrack_Third, 3, 0, 1, 1)
        self.comboBox_Disc_AudioTracks_Mixdown_First_Secondary = QtWidgets.QComboBox(self.groupBox_Disc_AudioTracks)
        self.comboBox_Disc_AudioTracks_Mixdown_First_Secondary.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_Disc_AudioTracks_Mixdown_First_Secondary.setObjectName("comboBox_Disc_AudioTracks_Mixdown_First_Secondary")
        self.gridLayout_6.addWidget(self.comboBox_Disc_AudioTracks_Mixdown_First_Secondary, 1, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_Disc_AudioTracks)
        self.groupBox_Disc_SubtitleTracks = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Disc_SubtitleTracks.sizePolicy().hasHeightForWidth())
        self.groupBox_Disc_SubtitleTracks.setSizePolicy(sizePolicy)
        self.groupBox_Disc_SubtitleTracks.setMinimumSize(QtCore.QSize(221, 161))
        self.groupBox_Disc_SubtitleTracks.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_Disc_SubtitleTracks.setObjectName("groupBox_Disc_SubtitleTracks")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_Disc_SubtitleTracks)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_Disc_SubtitleTracks_SelectTrack_First = QtWidgets.QComboBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Disc_SubtitleTracks_SelectTrack_First.sizePolicy().hasHeightForWidth())
        self.comboBox_Disc_SubtitleTracks_SelectTrack_First.setSizePolicy(sizePolicy)
        self.comboBox_Disc_SubtitleTracks_SelectTrack_First.setObjectName("comboBox_Disc_SubtitleTracks_SelectTrack_First")
        self.gridLayout_3.addWidget(self.comboBox_Disc_SubtitleTracks_SelectTrack_First, 1, 0, 1, 2)
        self.checkBox_Disc_SubtitleTracks_Burn_Third = QtWidgets.QCheckBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Disc_SubtitleTracks_Burn_Third.sizePolicy().hasHeightForWidth())
        self.checkBox_Disc_SubtitleTracks_Burn_Third.setSizePolicy(sizePolicy)
        self.checkBox_Disc_SubtitleTracks_Burn_Third.setText("")
        self.checkBox_Disc_SubtitleTracks_Burn_Third.setObjectName("checkBox_Disc_SubtitleTracks_Burn_Third")
        self.gridLayout_3.addWidget(self.checkBox_Disc_SubtitleTracks_Burn_Third, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Disc_SubtitleTracks_Forced_Second = QtWidgets.QCheckBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Disc_SubtitleTracks_Forced_Second.sizePolicy().hasHeightForWidth())
        self.checkBox_Disc_SubtitleTracks_Forced_Second.setSizePolicy(sizePolicy)
        self.checkBox_Disc_SubtitleTracks_Forced_Second.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkBox_Disc_SubtitleTracks_Forced_Second.setText("")
        self.checkBox_Disc_SubtitleTracks_Forced_Second.setObjectName("checkBox_Disc_SubtitleTracks_Forced_Second")
        self.gridLayout_3.addWidget(self.checkBox_Disc_SubtitleTracks_Forced_Second, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Disc_SubtitleTracks_Burn_Second = QtWidgets.QCheckBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Disc_SubtitleTracks_Burn_Second.sizePolicy().hasHeightForWidth())
        self.checkBox_Disc_SubtitleTracks_Burn_Second.setSizePolicy(sizePolicy)
        self.checkBox_Disc_SubtitleTracks_Burn_Second.setText("")
        self.checkBox_Disc_SubtitleTracks_Burn_Second.setObjectName("checkBox_Disc_SubtitleTracks_Burn_Second")
        self.gridLayout_3.addWidget(self.checkBox_Disc_SubtitleTracks_Burn_Second, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBox_Disc_SubtitleTracks_SelectTrack_Second = QtWidgets.QComboBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Disc_SubtitleTracks_SelectTrack_Second.sizePolicy().hasHeightForWidth())
        self.comboBox_Disc_SubtitleTracks_SelectTrack_Second.setSizePolicy(sizePolicy)
        self.comboBox_Disc_SubtitleTracks_SelectTrack_Second.setObjectName("comboBox_Disc_SubtitleTracks_SelectTrack_Second")
        self.gridLayout_3.addWidget(self.comboBox_Disc_SubtitleTracks_SelectTrack_Second, 2, 0, 1, 2)
        self.toolButton_Disc_Find_SubtitleTrack = QtWidgets.QToolButton(self.groupBox_Disc_SubtitleTracks)
        self.toolButton_Disc_Find_SubtitleTrack.setIcon(icon7)
        self.toolButton_Disc_Find_SubtitleTrack.setObjectName("toolButton_Disc_Find_SubtitleTrack")
        self.gridLayout_3.addWidget(self.toolButton_Disc_Find_SubtitleTrack, 0, 0, 1, 1)
        self.checkBox_Disc_SubtitleTracks_Default_Second = QtWidgets.QCheckBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Disc_SubtitleTracks_Default_Second.sizePolicy().hasHeightForWidth())
        self.checkBox_Disc_SubtitleTracks_Default_Second.setSizePolicy(sizePolicy)
        self.checkBox_Disc_SubtitleTracks_Default_Second.setText("")
        self.checkBox_Disc_SubtitleTracks_Default_Second.setObjectName("checkBox_Disc_SubtitleTracks_Default_Second")
        self.gridLayout_3.addWidget(self.checkBox_Disc_SubtitleTracks_Default_Second, 2, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Disc_SubtitleTracks_Forced_Third = QtWidgets.QCheckBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Disc_SubtitleTracks_Forced_Third.sizePolicy().hasHeightForWidth())
        self.checkBox_Disc_SubtitleTracks_Forced_Third.setSizePolicy(sizePolicy)
        self.checkBox_Disc_SubtitleTracks_Forced_Third.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkBox_Disc_SubtitleTracks_Forced_Third.setText("")
        self.checkBox_Disc_SubtitleTracks_Forced_Third.setObjectName("checkBox_Disc_SubtitleTracks_Forced_Third")
        self.gridLayout_3.addWidget(self.checkBox_Disc_SubtitleTracks_Forced_Third, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBox_Disc_SubtitleTracks_SelectTrack_Third = QtWidgets.QComboBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Disc_SubtitleTracks_SelectTrack_Third.sizePolicy().hasHeightForWidth())
        self.comboBox_Disc_SubtitleTracks_SelectTrack_Third.setSizePolicy(sizePolicy)
        self.comboBox_Disc_SubtitleTracks_SelectTrack_Third.setObjectName("comboBox_Disc_SubtitleTracks_SelectTrack_Third")
        self.gridLayout_3.addWidget(self.comboBox_Disc_SubtitleTracks_SelectTrack_Third, 3, 0, 1, 2)
        self.label_Disc_SubtitleTracks_Burn = QtWidgets.QLabel(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_SubtitleTracks_Burn.sizePolicy().hasHeightForWidth())
        self.label_Disc_SubtitleTracks_Burn.setSizePolicy(sizePolicy)
        self.label_Disc_SubtitleTracks_Burn.setMinimumSize(QtCore.QSize(45, 0))
        self.label_Disc_SubtitleTracks_Burn.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_Disc_SubtitleTracks_Burn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Disc_SubtitleTracks_Burn.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Disc_SubtitleTracks_Burn.setObjectName("label_Disc_SubtitleTracks_Burn")
        self.gridLayout_3.addWidget(self.label_Disc_SubtitleTracks_Burn, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Disc_SubtitleTracks_Default = QtWidgets.QLabel(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_SubtitleTracks_Default.sizePolicy().hasHeightForWidth())
        self.label_Disc_SubtitleTracks_Default.setSizePolicy(sizePolicy)
        self.label_Disc_SubtitleTracks_Default.setMinimumSize(QtCore.QSize(45, 0))
        self.label_Disc_SubtitleTracks_Default.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_Disc_SubtitleTracks_Default.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Disc_SubtitleTracks_Default.setObjectName("label_Disc_SubtitleTracks_Default")
        self.gridLayout_3.addWidget(self.label_Disc_SubtitleTracks_Default, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Disc_SubtitleTracks_Forced = QtWidgets.QLabel(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_SubtitleTracks_Forced.sizePolicy().hasHeightForWidth())
        self.label_Disc_SubtitleTracks_Forced.setSizePolicy(sizePolicy)
        self.label_Disc_SubtitleTracks_Forced.setMinimumSize(QtCore.QSize(45, 0))
        self.label_Disc_SubtitleTracks_Forced.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_Disc_SubtitleTracks_Forced.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Disc_SubtitleTracks_Forced.setObjectName("label_Disc_SubtitleTracks_Forced")
        self.gridLayout_3.addWidget(self.label_Disc_SubtitleTracks_Forced, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Disc_SubtitleTracks_Forced_First = QtWidgets.QCheckBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Disc_SubtitleTracks_Forced_First.sizePolicy().hasHeightForWidth())
        self.checkBox_Disc_SubtitleTracks_Forced_First.setSizePolicy(sizePolicy)
        self.checkBox_Disc_SubtitleTracks_Forced_First.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkBox_Disc_SubtitleTracks_Forced_First.setText("")
        self.checkBox_Disc_SubtitleTracks_Forced_First.setObjectName("checkBox_Disc_SubtitleTracks_Forced_First")
        self.gridLayout_3.addWidget(self.checkBox_Disc_SubtitleTracks_Forced_First, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Disc_SubtitleTracks_Default_First = QtWidgets.QCheckBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Disc_SubtitleTracks_Default_First.sizePolicy().hasHeightForWidth())
        self.checkBox_Disc_SubtitleTracks_Default_First.setSizePolicy(sizePolicy)
        self.checkBox_Disc_SubtitleTracks_Default_First.setText("")
        self.checkBox_Disc_SubtitleTracks_Default_First.setObjectName("checkBox_Disc_SubtitleTracks_Default_First")
        self.gridLayout_3.addWidget(self.checkBox_Disc_SubtitleTracks_Default_First, 1, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Disc_SubtitleTracks_Default_Third = QtWidgets.QCheckBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Disc_SubtitleTracks_Default_Third.sizePolicy().hasHeightForWidth())
        self.checkBox_Disc_SubtitleTracks_Default_Third.setSizePolicy(sizePolicy)
        self.checkBox_Disc_SubtitleTracks_Default_Third.setText("")
        self.checkBox_Disc_SubtitleTracks_Default_Third.setObjectName("checkBox_Disc_SubtitleTracks_Default_Third")
        self.gridLayout_3.addWidget(self.checkBox_Disc_SubtitleTracks_Default_Third, 3, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_Disc_SubtitleTracks_Burn_First = QtWidgets.QCheckBox(self.groupBox_Disc_SubtitleTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Disc_SubtitleTracks_Burn_First.sizePolicy().hasHeightForWidth())
        self.checkBox_Disc_SubtitleTracks_Burn_First.setSizePolicy(sizePolicy)
        self.checkBox_Disc_SubtitleTracks_Burn_First.setText("")
        self.checkBox_Disc_SubtitleTracks_Burn_First.setObjectName("checkBox_Disc_SubtitleTracks_Burn_First")
        self.gridLayout_3.addWidget(self.checkBox_Disc_SubtitleTracks_Burn_First, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.setColumnMinimumWidth(0, 80)
        self.horizontalLayout.addWidget(self.groupBox_Disc_SubtitleTracks)
        self.groupBox_Disc_Crop = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Disc_Crop.sizePolicy().hasHeightForWidth())
        self.groupBox_Disc_Crop.setSizePolicy(sizePolicy)
        self.groupBox_Disc_Crop.setMinimumSize(QtCore.QSize(241, 161))
        self.groupBox_Disc_Crop.setObjectName("groupBox_Disc_Crop")
        self.radioButton_Disc_Crop_Automatic = QtWidgets.QRadioButton(self.groupBox_Disc_Crop)
        self.radioButton_Disc_Crop_Automatic.setGeometry(QtCore.QRect(13, 33, 83, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_Disc_Crop_Automatic.sizePolicy().hasHeightForWidth())
        self.radioButton_Disc_Crop_Automatic.setSizePolicy(sizePolicy)
        self.radioButton_Disc_Crop_Automatic.setCheckable(True)
        self.radioButton_Disc_Crop_Automatic.setChecked(False)
        self.radioButton_Disc_Crop_Automatic.setObjectName("radioButton_Disc_Crop_Automatic")
        self.radioButton_Disc_Crop_Custom = QtWidgets.QRadioButton(self.groupBox_Disc_Crop)
        self.radioButton_Disc_Crop_Custom.setGeometry(QtCore.QRect(102, 33, 69, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_Disc_Crop_Custom.sizePolicy().hasHeightForWidth())
        self.radioButton_Disc_Crop_Custom.setSizePolicy(sizePolicy)
        self.radioButton_Disc_Crop_Custom.setChecked(True)
        self.radioButton_Disc_Crop_Custom.setObjectName("radioButton_Disc_Crop_Custom")
        self.toolButton_Disc_Find_Crop = QtWidgets.QToolButton(self.groupBox_Disc_Crop)
        self.toolButton_Disc_Find_Crop.setGeometry(QtCore.QRect(203, 33, 24, 23))
        self.toolButton_Disc_Find_Crop.setIcon(icon7)
        self.toolButton_Disc_Find_Crop.setObjectName("toolButton_Disc_Find_Crop")
        self.label_Disc_Crop_Top = QtWidgets.QLabel(self.groupBox_Disc_Crop)
        self.label_Disc_Crop_Top.setGeometry(QtCore.QRect(67, 68, 35, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_Crop_Top.sizePolicy().hasHeightForWidth())
        self.label_Disc_Crop_Top.setSizePolicy(sizePolicy)
        self.label_Disc_Crop_Top.setMinimumSize(QtCore.QSize(35, 0))
        self.label_Disc_Crop_Top.setMaximumSize(QtCore.QSize(35, 16777215))
        self.label_Disc_Crop_Top.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Disc_Crop_Top.setObjectName("label_Disc_Crop_Top")
        self.spinBox_Disc_Crop_Top = QtWidgets.QSpinBox(self.groupBox_Disc_Crop)
        self.spinBox_Disc_Crop_Top.setGeometry(QtCore.QRect(108, 64, 60, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Disc_Crop_Top.sizePolicy().hasHeightForWidth())
        self.spinBox_Disc_Crop_Top.setSizePolicy(sizePolicy)
        self.spinBox_Disc_Crop_Top.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_Disc_Crop_Top.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_Disc_Crop_Top.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Disc_Crop_Top.setMaximum(4096)
        self.spinBox_Disc_Crop_Top.setObjectName("spinBox_Disc_Crop_Top")
        self.label_Disc_Crop_Left = QtWidgets.QLabel(self.groupBox_Disc_Crop)
        self.label_Disc_Crop_Left.setGeometry(QtCore.QRect(13, 98, 23, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_Crop_Left.sizePolicy().hasHeightForWidth())
        self.label_Disc_Crop_Left.setSizePolicy(sizePolicy)
        self.label_Disc_Crop_Left.setMinimumSize(QtCore.QSize(0, 0))
        self.label_Disc_Crop_Left.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_Disc_Crop_Left.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Disc_Crop_Left.setObjectName("label_Disc_Crop_Left")
        self.spinBox_Disc_Crop_Left = QtWidgets.QSpinBox(self.groupBox_Disc_Crop)
        self.spinBox_Disc_Crop_Left.setGeometry(QtCore.QRect(42, 95, 60, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Disc_Crop_Left.sizePolicy().hasHeightForWidth())
        self.spinBox_Disc_Crop_Left.setSizePolicy(sizePolicy)
        self.spinBox_Disc_Crop_Left.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_Disc_Crop_Left.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_Disc_Crop_Left.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Disc_Crop_Left.setMaximum(4096)
        self.spinBox_Disc_Crop_Left.setObjectName("spinBox_Disc_Crop_Left")
        self.label_Disc_Crop_Right = QtWidgets.QLabel(self.groupBox_Disc_Crop)
        self.label_Disc_Crop_Right.setGeometry(QtCore.QRect(137, 98, 31, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_Crop_Right.sizePolicy().hasHeightForWidth())
        self.label_Disc_Crop_Right.setSizePolicy(sizePolicy)
        self.label_Disc_Crop_Right.setMinimumSize(QtCore.QSize(0, 0))
        self.label_Disc_Crop_Right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_Disc_Crop_Right.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Disc_Crop_Right.setObjectName("label_Disc_Crop_Right")
        self.spinBox_Disc_Crop_Right = QtWidgets.QSpinBox(self.groupBox_Disc_Crop)
        self.spinBox_Disc_Crop_Right.setGeometry(QtCore.QRect(174, 95, 60, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Disc_Crop_Right.sizePolicy().hasHeightForWidth())
        self.spinBox_Disc_Crop_Right.setSizePolicy(sizePolicy)
        self.spinBox_Disc_Crop_Right.setMinimumSize(QtCore.QSize(60, 23))
        self.spinBox_Disc_Crop_Right.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_Disc_Crop_Right.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Disc_Crop_Right.setMaximum(4096)
        self.spinBox_Disc_Crop_Right.setObjectName("spinBox_Disc_Crop_Right")
        self.label_Disc_Crop_Bottom = QtWidgets.QLabel(self.groupBox_Disc_Crop)
        self.label_Disc_Crop_Bottom.setGeometry(QtCore.QRect(59, 128, 43, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disc_Crop_Bottom.sizePolicy().hasHeightForWidth())
        self.label_Disc_Crop_Bottom.setSizePolicy(sizePolicy)
        self.label_Disc_Crop_Bottom.setMinimumSize(QtCore.QSize(0, 0))
        self.label_Disc_Crop_Bottom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_Disc_Crop_Bottom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Disc_Crop_Bottom.setObjectName("label_Disc_Crop_Bottom")
        self.spinBox_Disc_Crop_Bottom = QtWidgets.QSpinBox(self.groupBox_Disc_Crop)
        self.spinBox_Disc_Crop_Bottom.setGeometry(QtCore.QRect(108, 125, 60, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Disc_Crop_Bottom.sizePolicy().hasHeightForWidth())
        self.spinBox_Disc_Crop_Bottom.setSizePolicy(sizePolicy)
        self.spinBox_Disc_Crop_Bottom.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_Disc_Crop_Bottom.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_Disc_Crop_Bottom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Disc_Crop_Bottom.setMaximum(4096)
        self.spinBox_Disc_Crop_Bottom.setObjectName("spinBox_Disc_Crop_Bottom")
        self.horizontalLayout.addWidget(self.groupBox_Disc_Crop)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.tab_Disc)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_DiscTitles = QtWidgets.QSplitter(self.frame_3)
        self.splitter_DiscTitles.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_DiscTitles.setHandleWidth(9)
        self.splitter_DiscTitles.setChildrenCollapsible(False)
        self.splitter_DiscTitles.setObjectName("splitter_DiscTitles")
        self.tableWidget_Disc_Titles = QtWidgets.QTableWidget(self.splitter_DiscTitles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Disc_Titles.sizePolicy().hasHeightForWidth())
        self.tableWidget_Disc_Titles.setSizePolicy(sizePolicy)
        self.tableWidget_Disc_Titles.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidget_Disc_Titles.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Disc_Titles.setColumnCount(5)
        self.tableWidget_Disc_Titles.setObjectName("tableWidget_Disc_Titles")
        self.tableWidget_Disc_Titles.setRowCount(0)
        self.tableWidget_Disc_Titles.horizontalHeader().setDefaultSectionSize(20)
        self.tableWidget_Disc_Titles.verticalHeader().setVisible(False)
        self.tabWidget_Disc = QtWidgets.QTabWidget(self.splitter_DiscTitles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Disc.sizePolicy().hasHeightForWidth())
        self.tabWidget_Disc.setSizePolicy(sizePolicy)
        self.tabWidget_Disc.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tabWidget_Disc.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_Disc.setObjectName("tabWidget_Disc")
        self.tab_Disc_Title = QtWidgets.QWidget()
        self.tab_Disc_Title.setObjectName("tab_Disc_Title")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_Disc_Title)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_Disc_Title = QtWidgets.QTableWidget(self.tab_Disc_Title)
        self.tableWidget_Disc_Title.setMaximumSize(QtCore.QSize(175, 16777215))
        self.tableWidget_Disc_Title.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Disc_Title.setDragDropOverwriteMode(True)
        self.tableWidget_Disc_Title.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_Disc_Title.setWordWrap(False)
        self.tableWidget_Disc_Title.setCornerButtonEnabled(False)
        self.tableWidget_Disc_Title.setRowCount(10)
        self.tableWidget_Disc_Title.setColumnCount(2)
        self.tableWidget_Disc_Title.setObjectName("tableWidget_Disc_Title")
        self.tableWidget_Disc_Title.horizontalHeader().setVisible(False)
        self.tableWidget_Disc_Title.horizontalHeader().setDefaultSectionSize(20)
        self.tableWidget_Disc_Title.verticalHeader().setVisible(False)
        self.tableWidget_Disc_Title.verticalHeader().setDefaultSectionSize(21)
        self.gridLayout.addWidget(self.tableWidget_Disc_Title, 0, 0, 2, 1)
        self.tableWidget_Disc_Title_AudioTracks = QtWidgets.QTableWidget(self.tab_Disc_Title)
        self.tableWidget_Disc_Title_AudioTracks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Disc_Title_AudioTracks.setAlternatingRowColors(True)
        self.tableWidget_Disc_Title_AudioTracks.setColumnCount(2)
        self.tableWidget_Disc_Title_AudioTracks.setObjectName("tableWidget_Disc_Title_AudioTracks")
        self.tableWidget_Disc_Title_AudioTracks.setRowCount(0)
        self.tableWidget_Disc_Title_AudioTracks.verticalHeader().setVisible(False)
        self.tableWidget_Disc_Title_AudioTracks.verticalHeader().setDefaultSectionSize(21)
        self.gridLayout.addWidget(self.tableWidget_Disc_Title_AudioTracks, 0, 1, 1, 1)
        self.tableWidget_Disc_Title_SubtitleTracks = QtWidgets.QTableWidget(self.tab_Disc_Title)
        self.tableWidget_Disc_Title_SubtitleTracks.setColumnCount(2)
        self.tableWidget_Disc_Title_SubtitleTracks.setObjectName("tableWidget_Disc_Title_SubtitleTracks")
        self.tableWidget_Disc_Title_SubtitleTracks.setRowCount(0)
        self.tableWidget_Disc_Title_SubtitleTracks.verticalHeader().setVisible(False)
        self.tableWidget_Disc_Title_SubtitleTracks.verticalHeader().setDefaultSectionSize(21)
        self.gridLayout.addWidget(self.tableWidget_Disc_Title_SubtitleTracks, 1, 1, 1, 1)
        self.tabWidget_Disc.addTab(self.tab_Disc_Title, "")
        self.tab_Disc_Chapters = QtWidgets.QWidget()
        self.tab_Disc_Chapters.setObjectName("tab_Disc_Chapters")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_Disc_Chapters)
        self.gridLayout_9.setContentsMargins(11, 4, 11, 11)
        self.gridLayout_9.setHorizontalSpacing(6)
        self.gridLayout_9.setVerticalSpacing(4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_4 = QtWidgets.QFrame(self.tab_Disc_Chapters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 31))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setVerticalSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_Disc_Chapters_NoMarkers = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_Disc_Chapters_NoMarkers.setChecked(True)
        self.radioButton_Disc_Chapters_NoMarkers.setObjectName("radioButton_Disc_Chapters_NoMarkers")
        self.gridLayout_7.addWidget(self.radioButton_Disc_Chapters_NoMarkers, 0, 0, 1, 1)
        self.radioButton_Disc_Chapters_IncludeMarkers = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_Disc_Chapters_IncludeMarkers.setChecked(False)
        self.radioButton_Disc_Chapters_IncludeMarkers.setObjectName("radioButton_Disc_Chapters_IncludeMarkers")
        self.gridLayout_7.addWidget(self.radioButton_Disc_Chapters_IncludeMarkers, 0, 1, 1, 1)
        self.radioButton_Disc_Chapters_IncludeNames = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_Disc_Chapters_IncludeNames.setObjectName("radioButton_Disc_Chapters_IncludeNames")
        self.gridLayout_7.addWidget(self.radioButton_Disc_Chapters_IncludeNames, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 3, 1, 1)
        self.label_Disc_Chapters_FirstChapter = QtWidgets.QLabel(self.frame_4)
        self.label_Disc_Chapters_FirstChapter.setObjectName("label_Disc_Chapters_FirstChapter")
        self.gridLayout_7.addWidget(self.label_Disc_Chapters_FirstChapter, 0, 4, 1, 1)
        self.spinBox_Disc_Chapters_FirstChapter = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_Disc_Chapters_FirstChapter.setMinimum(1)
        self.spinBox_Disc_Chapters_FirstChapter.setMaximum(999)
        self.spinBox_Disc_Chapters_FirstChapter.setObjectName("spinBox_Disc_Chapters_FirstChapter")
        self.gridLayout_7.addWidget(self.spinBox_Disc_Chapters_FirstChapter, 0, 5, 1, 1)
        self.toolButton_Disc_Chapters_ResetFirstChapter = QtWidgets.QToolButton(self.frame_4)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/redo_2_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Disc_Chapters_ResetFirstChapter.setIcon(icon8)
        self.toolButton_Disc_Chapters_ResetFirstChapter.setObjectName("toolButton_Disc_Chapters_ResetFirstChapter")
        self.gridLayout_7.addWidget(self.toolButton_Disc_Chapters_ResetFirstChapter, 0, 6, 1, 1)
        self.gridLayout_9.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab_Disc_Chapters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 31))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setVerticalSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_Disc_Chapters_ImportChapterNames = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_Disc_Chapters_ImportChapterNames.setFlat(False)
        self.pushButton_Disc_Chapters_ImportChapterNames.setObjectName("pushButton_Disc_Chapters_ImportChapterNames")
        self.gridLayout_8.addWidget(self.pushButton_Disc_Chapters_ImportChapterNames, 0, 0, 1, 1)
        self.pushButton_Disc_Chapters_ExportChapterNames = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_Disc_Chapters_ExportChapterNames.setObjectName("pushButton_Disc_Chapters_ExportChapterNames")
        self.gridLayout_8.addWidget(self.pushButton_Disc_Chapters_ExportChapterNames, 0, 1, 1, 1)
        self.pushButton_Disc_Chapters_ResetNames = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_Disc_Chapters_ResetNames.setObjectName("pushButton_Disc_Chapters_ResetNames")
        self.gridLayout_8.addWidget(self.pushButton_Disc_Chapters_ResetNames, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 0, 3, 1, 1)
        self.pushButton_Disc_Chapters_SetTitleEnd = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_Disc_Chapters_SetTitleEnd.setObjectName("pushButton_Disc_Chapters_SetTitleEnd")
        self.gridLayout_8.addWidget(self.pushButton_Disc_Chapters_SetTitleEnd, 0, 4, 1, 1)
        self.gridLayout_9.addWidget(self.frame_5, 1, 0, 1, 1)
        self.tableWidget_Disc_Chapters = QtWidgets.QTableWidget(self.tab_Disc_Chapters)
        self.tableWidget_Disc_Chapters.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Disc_Chapters.setColumnCount(4)
        self.tableWidget_Disc_Chapters.setObjectName("tableWidget_Disc_Chapters")
        self.tableWidget_Disc_Chapters.setRowCount(0)
        self.tableWidget_Disc_Chapters.verticalHeader().setVisible(False)
        self.gridLayout_9.addWidget(self.tableWidget_Disc_Chapters, 2, 0, 1, 1)
        self.tabWidget_Disc.addTab(self.tab_Disc_Chapters, "")
        self.tab_Disc_ChapterRanges = QtWidgets.QWidget()
        self.tab_Disc_ChapterRanges.setObjectName("tab_Disc_ChapterRanges")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_Disc_ChapterRanges)
        self.gridLayout_12.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_6 = QtWidgets.QFrame(self.tab_Disc_ChapterRanges)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.radioButton_Disc_Title_AllChapters = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_Disc_Title_AllChapters.setObjectName("radioButton_Disc_Title_AllChapters")
        self.gridLayout_11.addWidget(self.radioButton_Disc_Title_AllChapters, 0, 0, 1, 1)
        self.radioButton_Disc_Title_ChapterRange = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_Disc_Title_ChapterRange.setObjectName("radioButton_Disc_Title_ChapterRange")
        self.gridLayout_11.addWidget(self.radioButton_Disc_Title_ChapterRange, 1, 0, 1, 1)
        self.radioButton_Disc_Title_Episodes = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_Disc_Title_Episodes.setObjectName("radioButton_Disc_Title_Episodes")
        self.gridLayout_11.addWidget(self.radioButton_Disc_Title_Episodes, 2, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_6, 0, 0, 1, 1)
        self.groupBox_Disc_Title_ChapterRanges = QtWidgets.QGroupBox(self.tab_Disc_ChapterRanges)
        self.groupBox_Disc_Title_ChapterRanges.setMaximumSize(QtCore.QSize(281, 69))
        self.groupBox_Disc_Title_ChapterRanges.setObjectName("groupBox_Disc_Title_ChapterRanges")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_Disc_Title_ChapterRanges)
        self.gridLayout_10.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_Disc_Title_ChapterRange_First = QtWidgets.QLabel(self.groupBox_Disc_Title_ChapterRanges)
        self.label_Disc_Title_ChapterRange_First.setObjectName("label_Disc_Title_ChapterRange_First")
        self.gridLayout_10.addWidget(self.label_Disc_Title_ChapterRange_First, 0, 0, 1, 1)
        self.spinBox_Disc_Title_ChapterRange_First = QtWidgets.QSpinBox(self.groupBox_Disc_Title_ChapterRanges)
        self.spinBox_Disc_Title_ChapterRange_First.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Disc_Title_ChapterRange_First.setMinimum(1)
        self.spinBox_Disc_Title_ChapterRange_First.setObjectName("spinBox_Disc_Title_ChapterRange_First")
        self.gridLayout_10.addWidget(self.spinBox_Disc_Title_ChapterRange_First, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(19, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem5, 0, 2, 1, 1)
        self.label_Disc_Title_ChapterRange_Last = QtWidgets.QLabel(self.groupBox_Disc_Title_ChapterRanges)
        self.label_Disc_Title_ChapterRange_Last.setObjectName("label_Disc_Title_ChapterRange_Last")
        self.gridLayout_10.addWidget(self.label_Disc_Title_ChapterRange_Last, 0, 3, 1, 1)
        self.spinBox_Disc_Title_ChapterRange_Last = QtWidgets.QSpinBox(self.groupBox_Disc_Title_ChapterRanges)
        self.spinBox_Disc_Title_ChapterRange_Last.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Disc_Title_ChapterRange_Last.setMinimum(1)
        self.spinBox_Disc_Title_ChapterRange_Last.setObjectName("spinBox_Disc_Title_ChapterRange_Last")
        self.gridLayout_10.addWidget(self.spinBox_Disc_Title_ChapterRange_Last, 0, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 0, 5, 1, 1)
        self.toolButton_Disc_Title_ChapterRange_Reset = QtWidgets.QToolButton(self.groupBox_Disc_Title_ChapterRanges)
        self.toolButton_Disc_Title_ChapterRange_Reset.setIcon(icon8)
        self.toolButton_Disc_Title_ChapterRange_Reset.setObjectName("toolButton_Disc_Title_ChapterRange_Reset")
        self.gridLayout_10.addWidget(self.toolButton_Disc_Title_ChapterRange_Reset, 0, 6, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_Disc_Title_ChapterRanges, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(144, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem7, 0, 2, 1, 1)
        self.groupBox_Disc_Title_Episodes = QtWidgets.QGroupBox(self.tab_Disc_ChapterRanges)
        self.groupBox_Disc_Title_Episodes.setMaximumSize(QtCore.QSize(16777215, 141))
        self.groupBox_Disc_Title_Episodes.setFlat(False)
        self.groupBox_Disc_Title_Episodes.setObjectName("groupBox_Disc_Title_Episodes")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_Disc_Title_Episodes)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_Disc_Title_Episodes = QtWidgets.QTableWidget(self.groupBox_Disc_Title_Episodes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Disc_Title_Episodes.sizePolicy().hasHeightForWidth())
        self.tableWidget_Disc_Title_Episodes.setSizePolicy(sizePolicy)
        self.tableWidget_Disc_Title_Episodes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Disc_Title_Episodes.setColumnCount(3)
        self.tableWidget_Disc_Title_Episodes.setObjectName("tableWidget_Disc_Title_Episodes")
        self.tableWidget_Disc_Title_Episodes.setRowCount(0)
        self.tableWidget_Disc_Title_Episodes.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tableWidget_Disc_Title_Episodes)
        self.frame_7 = QtWidgets.QFrame(self.groupBox_Disc_Title_Episodes)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolButton_Disc_Title_AddEpisode = QtWidgets.QToolButton(self.frame_7)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/add_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Disc_Title_AddEpisode.setIcon(icon9)
        self.toolButton_Disc_Title_AddEpisode.setObjectName("toolButton_Disc_Title_AddEpisode")
        self.verticalLayout_4.addWidget(self.toolButton_Disc_Title_AddEpisode)
        self.toolButton_Disc_Title_CopyEpisode = QtWidgets.QToolButton(self.frame_7)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/copying_and_distribution_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Disc_Title_CopyEpisode.setIcon(icon10)
        self.toolButton_Disc_Title_CopyEpisode.setObjectName("toolButton_Disc_Title_CopyEpisode")
        self.verticalLayout_4.addWidget(self.toolButton_Disc_Title_CopyEpisode)
        self.toolButton_Disc_Title_DeleteEpisode = QtWidgets.QToolButton(self.frame_7)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/delete_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Disc_Title_DeleteEpisode.setIcon(icon11)
        self.toolButton_Disc_Title_DeleteEpisode.setObjectName("toolButton_Disc_Title_DeleteEpisode")
        self.verticalLayout_4.addWidget(self.toolButton_Disc_Title_DeleteEpisode)
        spacerItem8 = QtWidgets.QSpacerItem(21, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.toolButton_Disc_Title_Episodes_DeleteAll = QtWidgets.QToolButton(self.frame_7)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/draw_eraser_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Disc_Title_Episodes_DeleteAll.setIcon(icon12)
        self.toolButton_Disc_Title_Episodes_DeleteAll.setObjectName("toolButton_Disc_Title_Episodes_DeleteAll")
        self.verticalLayout_4.addWidget(self.toolButton_Disc_Title_Episodes_DeleteAll)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.gridLayout_12.addWidget(self.groupBox_Disc_Title_Episodes, 1, 0, 1, 3)
        self.tabWidget_Disc.addTab(self.tab_Disc_ChapterRanges, "")
        self.tab_Disc_Title_AudioTracks = QtWidgets.QWidget()
        self.tab_Disc_Title_AudioTracks.setObjectName("tab_Disc_Title_AudioTracks")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_Disc_Title_AudioTracks)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.tab_Disc_Title_AudioTracks)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_Disc_Title_AudioTracks_Default = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_Disc_Title_AudioTracks_Default.setObjectName("radioButton_Disc_Title_AudioTracks_Default")
        self.horizontalLayout_3.addWidget(self.radioButton_Disc_Title_AudioTracks_Default)
        self.radioButton_Disc_Title_AudioTracks_Custom = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_Disc_Title_AudioTracks_Custom.setObjectName("radioButton_Disc_Title_AudioTracks_Custom")
        self.horizontalLayout_3.addWidget(self.radioButton_Disc_Title_AudioTracks_Custom)
        spacerItem9 = QtWidgets.QSpacerItem(295, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.toolButton_Disc_Title_AudoTracks_Clear = QtWidgets.QToolButton(self.frame_8)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("images/draw_eraser_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Disc_Title_AudoTracks_Clear.setIcon(icon13)
        self.toolButton_Disc_Title_AudoTracks_Clear.setObjectName("toolButton_Disc_Title_AudoTracks_Clear")
        self.horizontalLayout_3.addWidget(self.toolButton_Disc_Title_AudoTracks_Clear)
        self.toolButton_Disc_Title_AudioTracks_Find = QtWidgets.QToolButton(self.frame_8)
        self.toolButton_Disc_Title_AudioTracks_Find.setIcon(icon7)
        self.toolButton_Disc_Title_AudioTracks_Find.setObjectName("toolButton_Disc_Title_AudioTracks_Find")
        self.horizontalLayout_3.addWidget(self.toolButton_Disc_Title_AudioTracks_Find)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.tab_Disc_Title_AudioTracks)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_DiscTitle_AudioTracks_Primary = QtWidgets.QLabel(self.frame_9)
        self.label_DiscTitle_AudioTracks_Primary.setObjectName("label_DiscTitle_AudioTracks_Primary")
        self.gridLayout_13.addWidget(self.label_DiscTitle_AudioTracks_Primary, 0, 1, 1, 1)
        self.label_DiscTitle_AudioTracks_Secondary = QtWidgets.QLabel(self.frame_9)
        self.label_DiscTitle_AudioTracks_Secondary.setObjectName("label_DiscTitle_AudioTracks_Secondary")
        self.gridLayout_13.addWidget(self.label_DiscTitle_AudioTracks_Secondary, 0, 2, 1, 1)
        self.comboBox_DiscTitle_AudioTracks_SelectTrack_First = QtWidgets.QComboBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_DiscTitle_AudioTracks_SelectTrack_First.sizePolicy().hasHeightForWidth())
        self.comboBox_DiscTitle_AudioTracks_SelectTrack_First.setSizePolicy(sizePolicy)
        self.comboBox_DiscTitle_AudioTracks_SelectTrack_First.setObjectName("comboBox_DiscTitle_AudioTracks_SelectTrack_First")
        self.gridLayout_13.addWidget(self.comboBox_DiscTitle_AudioTracks_SelectTrack_First, 1, 0, 1, 1)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_First_Primary = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_First_Primary.setObjectName("comboBox_DiscTitle_AudioTracks_Mixdown_First_Primary")
        self.gridLayout_13.addWidget(self.comboBox_DiscTitle_AudioTracks_Mixdown_First_Primary, 1, 1, 1, 1)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_First_Secondary = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_First_Secondary.setObjectName("comboBox_DiscTitle_AudioTracks_Mixdown_First_Secondary")
        self.gridLayout_13.addWidget(self.comboBox_DiscTitle_AudioTracks_Mixdown_First_Secondary, 1, 2, 1, 1)
        self.comboBox_DiscTitle_AudioTracks_SelectTrack_Second = QtWidgets.QComboBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_DiscTitle_AudioTracks_SelectTrack_Second.sizePolicy().hasHeightForWidth())
        self.comboBox_DiscTitle_AudioTracks_SelectTrack_Second.setSizePolicy(sizePolicy)
        self.comboBox_DiscTitle_AudioTracks_SelectTrack_Second.setObjectName("comboBox_DiscTitle_AudioTracks_SelectTrack_Second")
        self.gridLayout_13.addWidget(self.comboBox_DiscTitle_AudioTracks_SelectTrack_Second, 2, 0, 1, 1)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_Second_Primary = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_Second_Primary.setObjectName("comboBox_DiscTitle_AudioTracks_Mixdown_Second_Primary")
        self.gridLayout_13.addWidget(self.comboBox_DiscTitle_AudioTracks_Mixdown_Second_Primary, 2, 1, 1, 1)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_Second_Secondary = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_Second_Secondary.setObjectName("comboBox_DiscTitle_AudioTracks_Mixdown_Second_Secondary")
        self.gridLayout_13.addWidget(self.comboBox_DiscTitle_AudioTracks_Mixdown_Second_Secondary, 2, 2, 1, 1)
        self.comboBox_DiscTitle_AudioTracks_SelectTrack_Third = QtWidgets.QComboBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_DiscTitle_AudioTracks_SelectTrack_Third.sizePolicy().hasHeightForWidth())
        self.comboBox_DiscTitle_AudioTracks_SelectTrack_Third.setSizePolicy(sizePolicy)
        self.comboBox_DiscTitle_AudioTracks_SelectTrack_Third.setObjectName("comboBox_DiscTitle_AudioTracks_SelectTrack_Third")
        self.gridLayout_13.addWidget(self.comboBox_DiscTitle_AudioTracks_SelectTrack_Third, 3, 0, 1, 1)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_Third_Primary = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_Third_Primary.setObjectName("comboBox_DiscTitle_AudioTracks_Mixdown_Third_Primary")
        self.gridLayout_13.addWidget(self.comboBox_DiscTitle_AudioTracks_Mixdown_Third_Primary, 3, 1, 1, 1)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_Third_Secondary = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_DiscTitle_AudioTracks_Mixdown_Third_Secondary.setObjectName("comboBox_DiscTitle_AudioTracks_Mixdown_Third_Secondary")
        self.gridLayout_13.addWidget(self.comboBox_DiscTitle_AudioTracks_Mixdown_Third_Secondary, 3, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_9)
        spacerItem10 = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.tabWidget_Disc.addTab(self.tab_Disc_Title_AudioTracks, "")
        self.horizontalLayout_4.addWidget(self.splitter_DiscTitles)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_Disc, "")
        self.tab_MakeItSo = QtWidgets.QWidget()
        self.tab_MakeItSo.setObjectName("tab_MakeItSo")
        self.tabWidget.addTab(self.tab_MakeItSo, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1150, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionBrowse_for_Video = QtWidgets.QAction(MainWindow)
        self.actionBrowse_for_Video.setObjectName("actionBrowse_for_Video")
        self.actionBrowse_for_Destination = QtWidgets.QAction(MainWindow)
        self.actionBrowse_for_Destination.setObjectName("actionBrowse_for_Destination")
        self.actionSave_Session = QtWidgets.QAction(MainWindow)
        self.actionSave_Session.setObjectName("actionSave_Session")
        self.actionSave_Session_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Session_As.setObjectName("actionSave_Session_As")
        self.actionSave_Temporary_Session = QtWidgets.QAction(MainWindow)
        self.actionSave_Temporary_Session.setObjectName("actionSave_Temporary_Session")
        self.actionSave_Hash_Session = QtWidgets.QAction(MainWindow)
        self.actionSave_Hash_Session.setObjectName("actionSave_Hash_Session")
        self.actionDelete_Hash_Session = QtWidgets.QAction(MainWindow)
        self.actionDelete_Hash_Session.setObjectName("actionDelete_Hash_Session")
        self.actionOpen_Session = QtWidgets.QAction(MainWindow)
        self.actionOpen_Session.setObjectName("actionOpen_Session")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionBrowse_for_Video)
        self.menuFile.addAction(self.actionBrowse_for_Destination)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Session)
        self.menuFile.addAction(self.actionSave_Session_As)
        self.menuFile.addAction(self.actionSave_Temporary_Session)
        self.menuFile.addAction(self.actionSave_Hash_Session)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDelete_Hash_Session)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Session)
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.label_Disc_Title.setBuddy(self.lineEdit_Disc_Title)
        self.label_Disc_FirstEpisode.setBuddy(self.spinBox_Disc_FirstEpisode)
        self.label_Disc_Mask.setBuddy(self.comboBox_Disc_Mask)
        self.label_Disc_EpisodeNumberPrecision.setBuddy(self.spinBox_Disc_EpisodeNumberPrecision)
        self.label_Disc_Crop_Top.setBuddy(self.spinBox_Disc_Crop_Top)
        self.label_Disc_Crop_Left.setBuddy(self.spinBox_Disc_Crop_Left)
        self.label_Disc_Crop_Right.setBuddy(self.spinBox_Disc_Crop_Right)
        self.label_Disc_Crop_Bottom.setBuddy(self.spinBox_Disc_Crop_Bottom)
        self.label_Disc_Chapters_FirstChapter.setBuddy(self.spinBox_Disc_Chapters_FirstChapter)
        self.label_Disc_Title_ChapterRange_First.setBuddy(self.spinBox_Disc_Title_ChapterRange_First)
        self.label_Disc_Title_ChapterRange_Last.setBuddy(self.spinBox_Disc_Title_ChapterRange_Last)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_Disc.setCurrentIndex(3)
        self.radioButton_Disc_Crop_Automatic.toggled['bool'].connect(self.spinBox_Disc_Crop_Top.setDisabled)
        self.radioButton_Disc_Crop_Automatic.toggled['bool'].connect(self.spinBox_Disc_Crop_Left.setDisabled)
        self.radioButton_Disc_Crop_Automatic.toggled['bool'].connect(self.spinBox_Disc_Crop_Right.setDisabled)
        self.radioButton_Disc_Crop_Automatic.toggled['bool'].connect(self.spinBox_Disc_Crop_Bottom.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QtHEP"))
        self.label_Disc_Source.setText(_translate("MainWindow", "Source"))
        self.lineEdit_Disc_Source.setToolTip(_translate("MainWindow", "A folder containing the video source."))
        self.pushButton_Disc_Source_Browse.setToolTip(_translate("MainWindow", "Select and scan the folder containing the video to be transcoded."))
        self.pushButton_Disc_Source_Browse.setText(_translate("MainWindow", "Browse"))
        self.toolButton_Disc_RunVLC.setToolTip(_translate("MainWindow", "Play the source with VLC."))
        self.toolButton_Disc_RunVLC.setText(_translate("MainWindow", "..."))
        self.toolButton_Disc_Source_Read.setToolTip(_translate("MainWindow", "Re-scan the source."))
        self.toolButton_Disc_Source_Read.setText(_translate("MainWindow", "..."))
        self.toolButton_Disc_Source_Find.setToolTip(_translate("MainWindow", "Find a new location for the  source but don\'t re-scan it."))
        self.toolButton_Disc_Source_Find.setText(_translate("MainWindow", "..."))
        self.toolButton_Disc_UpdateHash.setToolTip(_translate("MainWindow", "Update the hash value for the source."))
        self.toolButton_Disc_UpdateHash.setText(_translate("MainWindow", "..."))
        self.label_Disc_DiskLabel.setText(_translate("MainWindow", "Disk"))
        self.toolButton_Disc_GetSourceDiskLabel.setToolTip(_translate("MainWindow", "Get the label for the source disk."))
        self.toolButton_Disc_GetSourceDiskLabel.setText(_translate("MainWindow", "..."))
        self.toolButton_Disc_EditSourceDiskLabel.setToolTip(_translate("MainWindow", "Manually enter a source disk label"))
        self.toolButton_Disc_EditSourceDiskLabel.setText(_translate("MainWindow", "..."))
        self.label_Disc_Destination.setText(_translate("MainWindow", "Destination"))
        self.lineEdit_Disc_Destination.setToolTip(_translate("MainWindow", "A folder where the transcoded files wil be stored."))
        self.pushButton_Disc_Destination_Browse.setToolTip(_translate("MainWindow", "Select the folder where the transcoded files wil be stored."))
        self.pushButton_Disc_Destination_Browse.setText(_translate("MainWindow", "Browse"))
        self.checkBox_Disc_NoDVDNAV.setToolTip(_translate("MainWindow", "Add the NODVDNAV  switch to the HandBrake command line."))
        self.checkBox_Disc_NoDVDNAV.setText(_translate("MainWindow", "No DVDNAV"))
        self.groupBox_Disc_FileName.setTitle(_translate("MainWindow", "File Name"))
        self.label_Disc_Title.setText(_translate("MainWindow", "Title"))
        self.lineEdit_Disc_Title.setToolTip(_translate("MainWindow", "The title piece of the video file name."))
        self.label_Disc_FirstEpisode.setText(_translate("MainWindow", "First Episode"))
        self.spinBox_Disc_FirstEpisode.setToolTip(_translate("MainWindow", "The starting number for the episode number piece of the video file name.,"))
        self.toolButton_ResetFirstEpisode.setToolTip(_translate("MainWindow", "Reset the first episode number."))
        self.toolButton_ResetFirstEpisode.setText(_translate("MainWindow", "..."))
        self.label_Disc_Mask.setText(_translate("MainWindow", "Mask"))
        self.comboBox_Disc_Mask.setToolTip(_translate("MainWindow", "The mask used to build the video file name."))
        self.label_Disc_EpisodeNumberPrecision.setText(_translate("MainWindow", "Precision"))
        self.spinBox_Disc_EpisodeNumberPrecision.setToolTip(_translate("MainWindow", "The precision (length) of the episode number piece of the video file name."))
        self.toolButton_ResetEpisodeNumberPrecision.setToolTip(_translate("MainWindow", "Reset the episode number precision."))
        self.toolButton_ResetEpisodeNumberPrecision.setText(_translate("MainWindow", "..."))
        self.groupBox_Disc_Notes.setTitle(_translate("MainWindow", "Notes"))
        self.groupBox_Processing.setTitle(_translate("MainWindow", "Processing"))
        self.label_Disc_Preset.setText(_translate("MainWindow", "Preset"))
        self.groupBox_Disc_AudioTracks.setTitle(_translate("MainWindow", "Audio Tracks"))
        self.toolButton_Disc_Find_AudioTracks.setToolTip(_translate("MainWindow", "Select audio tracks from the first selected title."))
        self.toolButton_Disc_Find_AudioTracks.setText(_translate("MainWindow", "..."))
        self.label_Disc_AudioTracks_Primary.setText(_translate("MainWindow", "Primary"))
        self.label_Disc_AudioTracks_Secondary.setText(_translate("MainWindow", "Secondary"))
        self.groupBox_Disc_SubtitleTracks.setTitle(_translate("MainWindow", "Subtitle Tracks"))
        self.toolButton_Disc_Find_SubtitleTrack.setToolTip(_translate("MainWindow", "Find the subtitle track for the first selected title."))
        self.toolButton_Disc_Find_SubtitleTrack.setText(_translate("MainWindow", "..."))
        self.label_Disc_SubtitleTracks_Burn.setText(_translate("MainWindow", "Burn"))
        self.label_Disc_SubtitleTracks_Default.setText(_translate("MainWindow", "Default"))
        self.label_Disc_SubtitleTracks_Forced.setText(_translate("MainWindow", "Forced"))
        self.groupBox_Disc_Crop.setTitle(_translate("MainWindow", "Cropping"))
        self.radioButton_Disc_Crop_Automatic.setToolTip(_translate("MainWindow", "Let HandBrake automatically crop the title(s)."))
        self.radioButton_Disc_Crop_Automatic.setText(_translate("MainWindow", "Automatic"))
        self.radioButton_Disc_Crop_Custom.setToolTip(_translate("MainWindow", "Use these cropping values for all titles."))
        self.radioButton_Disc_Crop_Custom.setText(_translate("MainWindow", "Custom"))
        self.toolButton_Disc_Find_Crop.setToolTip(_translate("MainWindow", "<html><head/><body><p>Find the cropping values; the values from the first selected title will be used.</p></body></html>"))
        self.toolButton_Disc_Find_Crop.setText(_translate("MainWindow", "..."))
        self.label_Disc_Crop_Top.setText(_translate("MainWindow", "Top"))
        self.label_Disc_Crop_Left.setText(_translate("MainWindow", "Left"))
        self.label_Disc_Crop_Right.setText(_translate("MainWindow", "Right"))
        self.label_Disc_Crop_Bottom.setText(_translate("MainWindow", "Bottom"))
        self.tabWidget_Disc.setTabText(self.tabWidget_Disc.indexOf(self.tab_Disc_Title), _translate("MainWindow", "Title"))
        self.radioButton_Disc_Chapters_NoMarkers.setToolTip(_translate("MainWindow", "No chapter markers in the video file."))
        self.radioButton_Disc_Chapters_NoMarkers.setText(_translate("MainWindow", "No markers"))
        self.radioButton_Disc_Chapters_IncludeMarkers.setToolTip(_translate("MainWindow", "Let HandBrake create the standard chapter markers in the video file."))
        self.radioButton_Disc_Chapters_IncludeMarkers.setText(_translate("MainWindow", "Include markers"))
        self.radioButton_Disc_Chapters_IncludeNames.setToolTip(_translate("MainWindow", "Add custom chapter names to the video file."))
        self.radioButton_Disc_Chapters_IncludeNames.setText(_translate("MainWindow", "Include names"))
        self.label_Disc_Chapters_FirstChapter.setText(_translate("MainWindow", "First chapter "))
        self.spinBox_Disc_Chapters_FirstChapter.setToolTip(_translate("MainWindow", "Starting number for chapters."))
        self.toolButton_Disc_Chapters_ResetFirstChapter.setToolTip(_translate("MainWindow", "Reset the first chapter number."))
        self.toolButton_Disc_Chapters_ResetFirstChapter.setText(_translate("MainWindow", "..."))
        self.pushButton_Disc_Chapters_ImportChapterNames.setToolTip(_translate("MainWindow", "Import chapter names from a ChaptersDB,org text file."))
        self.pushButton_Disc_Chapters_ImportChapterNames.setText(_translate("MainWindow", "Import"))
        self.pushButton_Disc_Chapters_ExportChapterNames.setToolTip(_translate("MainWindow", "Export the chapter names to a text file."))
        self.pushButton_Disc_Chapters_ExportChapterNames.setText(_translate("MainWindow", "Export"))
        self.pushButton_Disc_Chapters_ResetNames.setToolTip(_translate("MainWindow", "Reset the chapter names to their default names."))
        self.pushButton_Disc_Chapters_ResetNames.setText(_translate("MainWindow", "Reset"))
        self.pushButton_Disc_Chapters_SetTitleEnd.setToolTip(_translate("MainWindow", "Set a short last chapter name to the preferences value."))
        self.pushButton_Disc_Chapters_SetTitleEnd.setText(_translate("MainWindow", "Set Title End"))
        self.tabWidget_Disc.setTabText(self.tabWidget_Disc.indexOf(self.tab_Disc_Chapters), _translate("MainWindow", "Chapters"))
        self.radioButton_Disc_Title_AllChapters.setToolTip(_translate("MainWindow", "Use all chapters when encoding the video."))
        self.radioButton_Disc_Title_AllChapters.setText(_translate("MainWindow", "All"))
        self.radioButton_Disc_Title_ChapterRange.setToolTip(_translate("MainWindow", "Use a limited range of chapters when encoding the video."))
        self.radioButton_Disc_Title_ChapterRange.setText(_translate("MainWindow", "Range"))
        self.radioButton_Disc_Title_Episodes.setToolTip(_translate("MainWindow", "Encode a series of videos from the chapters."))
        self.radioButton_Disc_Title_Episodes.setText(_translate("MainWindow", "Episodes"))
        self.groupBox_Disc_Title_ChapterRanges.setTitle(_translate("MainWindow", "Range"))
        self.label_Disc_Title_ChapterRange_First.setText(_translate("MainWindow", "First"))
        self.label_Disc_Title_ChapterRange_Last.setText(_translate("MainWindow", "Last"))
        self.toolButton_Disc_Title_ChapterRange_Reset.setToolTip(_translate("MainWindow", "Reset the chapter ranges."))
        self.toolButton_Disc_Title_ChapterRange_Reset.setText(_translate("MainWindow", "..."))
        self.groupBox_Disc_Title_Episodes.setTitle(_translate("MainWindow", "Episodes"))
        self.toolButton_Disc_Title_AddEpisode.setText(_translate("MainWindow", "..."))
        self.toolButton_Disc_Title_CopyEpisode.setText(_translate("MainWindow", "..."))
        self.toolButton_Disc_Title_DeleteEpisode.setText(_translate("MainWindow", "..."))
        self.toolButton_Disc_Title_Episodes_DeleteAll.setToolTip(_translate("MainWindow", "Reset all of the chapter ranges."))
        self.toolButton_Disc_Title_Episodes_DeleteAll.setText(_translate("MainWindow", "..."))
        self.tabWidget_Disc.setTabText(self.tabWidget_Disc.indexOf(self.tab_Disc_ChapterRanges), _translate("MainWindow", "Chapter Ranges"))
        self.radioButton_Disc_Title_AudioTracks_Default.setToolTip(_translate("MainWindow", "Use the disc (global) audio track mixdowns."))
        self.radioButton_Disc_Title_AudioTracks_Default.setText(_translate("MainWindow", "Default"))
        self.radioButton_Disc_Title_AudioTracks_Custom.setToolTip(_translate("MainWindow", "Use custom audio track mixdowns for the selected title."))
        self.radioButton_Disc_Title_AudioTracks_Custom.setText(_translate("MainWindow", "Custom"))
        self.toolButton_Disc_Title_AudoTracks_Clear.setToolTip(_translate("MainWindow", "Clear the custom audio track mixdowns for the selected title."))
        self.toolButton_Disc_Title_AudoTracks_Clear.setText(_translate("MainWindow", "..."))
        self.toolButton_Disc_Title_AudioTracks_Find.setToolTip(_translate("MainWindow", "Find and set custom audio track mixdowns for the current title."))
        self.toolButton_Disc_Title_AudioTracks_Find.setText(_translate("MainWindow", "..."))
        self.label_DiscTitle_AudioTracks_Primary.setText(_translate("MainWindow", "Primary"))
        self.label_DiscTitle_AudioTracks_Secondary.setText(_translate("MainWindow", "Secondary"))
        self.tabWidget_Disc.setTabText(self.tabWidget_Disc.indexOf(self.tab_Disc_Title_AudioTracks), _translate("MainWindow", "Audio Tracks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Disc), _translate("MainWindow", "Disc"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_MakeItSo), _translate("MainWindow", "Make It So"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionBrowse_for_Video.setText(_translate("MainWindow", "Browse for Video"))
        self.actionBrowse_for_Video.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionBrowse_for_Destination.setText(_translate("MainWindow", "Browse for Destination"))
        self.actionSave_Session.setText(_translate("MainWindow", "Save Session"))
        self.actionSave_Session.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_Session_As.setText(_translate("MainWindow", "Save Session As..."))
        self.actionSave_Temporary_Session.setText(_translate("MainWindow", "Save Temporary Session"))
        self.actionSave_Temporary_Session.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionSave_Hash_Session.setText(_translate("MainWindow", "Save Hash Session"))
        self.actionSave_Hash_Session.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionDelete_Hash_Session.setText(_translate("MainWindow", "Delete Hash Session"))
        self.actionOpen_Session.setText(_translate("MainWindow", "Open Session..."))
        self.actionOpen_Session.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen_Recent.setText(_translate("MainWindow", "Open Recent"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

