# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogPreferences(object):
    def setupUi(self, DialogPreferences):
        DialogPreferences.setObjectName("DialogPreferences")
        DialogPreferences.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogPreferences.resize(640, 520)
        self.gridLayout = QtWidgets.QGridLayout(DialogPreferences)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogPreferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(DialogPreferences)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_General = QtWidgets.QWidget()
        self.tab_General.setObjectName("tab_General")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_General)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_Executables = QtWidgets.QGroupBox(self.tab_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Executables.sizePolicy().hasHeightForWidth())
        self.groupBox_Executables.setSizePolicy(sizePolicy)
        self.groupBox_Executables.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_Executables.setObjectName("groupBox_Executables")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_Executables)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_HandBrakeCLI = QtWidgets.QLabel(self.groupBox_Executables)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_HandBrakeCLI.sizePolicy().hasHeightForWidth())
        self.label_HandBrakeCLI.setSizePolicy(sizePolicy)
        self.label_HandBrakeCLI.setScaledContents(False)
        self.label_HandBrakeCLI.setObjectName("label_HandBrakeCLI")
        self.gridLayout_2.addWidget(self.label_HandBrakeCLI, 0, 0, 1, 1)
        self.lineEdit_HandBrakeCLI = QtWidgets.QLineEdit(self.groupBox_Executables)
        self.lineEdit_HandBrakeCLI.setText("")
        self.lineEdit_HandBrakeCLI.setClearButtonEnabled(True)
        self.lineEdit_HandBrakeCLI.setObjectName("lineEdit_HandBrakeCLI")
        self.gridLayout_2.addWidget(self.lineEdit_HandBrakeCLI, 0, 1, 1, 1)
        self.pushButton_BrowseHandBrakeCLI = QtWidgets.QPushButton(self.groupBox_Executables)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_BrowseHandBrakeCLI.sizePolicy().hasHeightForWidth())
        self.pushButton_BrowseHandBrakeCLI.setSizePolicy(sizePolicy)
        self.pushButton_BrowseHandBrakeCLI.setObjectName("pushButton_BrowseHandBrakeCLI")
        self.gridLayout_2.addWidget(self.pushButton_BrowseHandBrakeCLI, 0, 2, 1, 1)
        self.label_VLC = QtWidgets.QLabel(self.groupBox_Executables)
        self.label_VLC.setObjectName("label_VLC")
        self.gridLayout_2.addWidget(self.label_VLC, 1, 0, 1, 1)
        self.lineEdit_VLC = QtWidgets.QLineEdit(self.groupBox_Executables)
        self.lineEdit_VLC.setClearButtonEnabled(True)
        self.lineEdit_VLC.setObjectName("lineEdit_VLC")
        self.gridLayout_2.addWidget(self.lineEdit_VLC, 1, 1, 1, 1)
        self.pushButton_BrowseVLC = QtWidgets.QPushButton(self.groupBox_Executables)
        self.pushButton_BrowseVLC.setObjectName("pushButton_BrowseVLC")
        self.gridLayout_2.addWidget(self.pushButton_BrowseVLC, 1, 2, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_Executables)
        self.groupBox_Logging = QtWidgets.QGroupBox(self.tab_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Logging.sizePolicy().hasHeightForWidth())
        self.groupBox_Logging.setSizePolicy(sizePolicy)
        self.groupBox_Logging.setObjectName("groupBox_Logging")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_Logging)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_LogHandBrakeAnalysis = QtWidgets.QCheckBox(self.groupBox_Logging)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_LogHandBrakeAnalysis.sizePolicy().hasHeightForWidth())
        self.checkBox_LogHandBrakeAnalysis.setSizePolicy(sizePolicy)
        self.checkBox_LogHandBrakeAnalysis.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_LogHandBrakeAnalysis.setObjectName("checkBox_LogHandBrakeAnalysis")
        self.gridLayout_3.addWidget(self.checkBox_LogHandBrakeAnalysis, 0, 0, 1, 1)
        self.checkBox_LogHandBrakeTranscoding = QtWidgets.QCheckBox(self.groupBox_Logging)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_LogHandBrakeTranscoding.sizePolicy().hasHeightForWidth())
        self.checkBox_LogHandBrakeTranscoding.setSizePolicy(sizePolicy)
        self.checkBox_LogHandBrakeTranscoding.setObjectName("checkBox_LogHandBrakeTranscoding")
        self.gridLayout_3.addWidget(self.checkBox_LogHandBrakeTranscoding, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_LogFile = QtWidgets.QLabel(self.groupBox_Logging)
        self.label_LogFile.setObjectName("label_LogFile")
        self.horizontalLayout_2.addWidget(self.label_LogFile)
        self.lineEdit_LogFilename = QtWidgets.QLineEdit(self.groupBox_Logging)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_LogFilename.sizePolicy().hasHeightForWidth())
        self.lineEdit_LogFilename.setSizePolicy(sizePolicy)
        self.lineEdit_LogFilename.setClearButtonEnabled(True)
        self.lineEdit_LogFilename.setObjectName("lineEdit_LogFilename")
        self.horizontalLayout_2.addWidget(self.lineEdit_LogFilename)
        self.pushButton_BrowseLogFile = QtWidgets.QPushButton(self.groupBox_Logging)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_BrowseLogFile.sizePolicy().hasHeightForWidth())
        self.pushButton_BrowseLogFile.setSizePolicy(sizePolicy)
        self.pushButton_BrowseLogFile.setObjectName("pushButton_BrowseLogFile")
        self.horizontalLayout_2.addWidget(self.pushButton_BrowseLogFile)
        self.pushButton_ClearLogFile = QtWidgets.QPushButton(self.groupBox_Logging)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ClearLogFile.sizePolicy().hasHeightForWidth())
        self.pushButton_ClearLogFile.setSizePolicy(sizePolicy)
        self.pushButton_ClearLogFile.setObjectName("pushButton_ClearLogFile")
        self.horizontalLayout_2.addWidget(self.pushButton_ClearLogFile)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_Logging)
        self.groupBox_Options = QtWidgets.QGroupBox(self.tab_General)
        self.groupBox_Options.setObjectName("groupBox_Options")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_Options)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_ChapterNameNumbers = QtWidgets.QCheckBox(self.groupBox_Options)
        self.checkBox_ChapterNameNumbers.setObjectName("checkBox_ChapterNameNumbers")
        self.gridLayout_4.addWidget(self.checkBox_ChapterNameNumbers, 0, 0, 1, 1)
        self.checkBox_MP4StreamWarning = QtWidgets.QCheckBox(self.groupBox_Options)
        self.checkBox_MP4StreamWarning.setObjectName("checkBox_MP4StreamWarning")
        self.gridLayout_4.addWidget(self.checkBox_MP4StreamWarning, 1, 0, 1, 1)
        self.checkBox_SetShortLastChapter = QtWidgets.QCheckBox(self.groupBox_Options)
        self.checkBox_SetShortLastChapter.setObjectName("checkBox_SetShortLastChapter")
        self.gridLayout_4.addWidget(self.checkBox_SetShortLastChapter, 2, 0, 1, 1)
        self.lineEdit_ShortLastChapter = QtWidgets.QLineEdit(self.groupBox_Options)
        self.lineEdit_ShortLastChapter.setClearButtonEnabled(True)
        self.lineEdit_ShortLastChapter.setObjectName("lineEdit_ShortLastChapter")
        self.gridLayout_4.addWidget(self.lineEdit_ShortLastChapter, 2, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_Options)
        spacerItem = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_General, "")
        self.tab_Filename = QtWidgets.QWidget()
        self.tab_Filename.setObjectName("tab_Filename")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_Filename)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_FilenameTemplates = QtWidgets.QGroupBox(self.tab_Filename)
        self.groupBox_FilenameTemplates.setObjectName("groupBox_FilenameTemplates")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_FilenameTemplates)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listWidget_FilenameTemplates = QtWidgets.QListWidget(self.groupBox_FilenameTemplates)
        self.listWidget_FilenameTemplates.setTabKeyNavigation(True)
        self.listWidget_FilenameTemplates.setAlternatingRowColors(True)
        self.listWidget_FilenameTemplates.setSelectionRectVisible(True)
        self.listWidget_FilenameTemplates.setObjectName("listWidget_FilenameTemplates")
        self.horizontalLayout_3.addWidget(self.listWidget_FilenameTemplates)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolButton_FilenameTemplateAdd = QtWidgets.QToolButton(self.groupBox_FilenameTemplates)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/add_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_FilenameTemplateAdd.setIcon(icon)
        self.toolButton_FilenameTemplateAdd.setObjectName("toolButton_FilenameTemplateAdd")
        self.verticalLayout.addWidget(self.toolButton_FilenameTemplateAdd)
        self.toolButton_FilenameTemplateCopy = QtWidgets.QToolButton(self.groupBox_FilenameTemplates)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/copying_and_distribution_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_FilenameTemplateCopy.setIcon(icon1)
        self.toolButton_FilenameTemplateCopy.setObjectName("toolButton_FilenameTemplateCopy")
        self.verticalLayout.addWidget(self.toolButton_FilenameTemplateCopy)
        self.toolButton_FilenameTemplateDelete = QtWidgets.QToolButton(self.groupBox_FilenameTemplates)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/delete_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_FilenameTemplateDelete.setIcon(icon2)
        self.toolButton_FilenameTemplateDelete.setObjectName("toolButton_FilenameTemplateDelete")
        self.verticalLayout.addWidget(self.toolButton_FilenameTemplateDelete)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.toolButton_FilenameTemplateMoveTop = QtWidgets.QToolButton(self.groupBox_FilenameTemplates)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/move_top_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_FilenameTemplateMoveTop.setIcon(icon3)
        self.toolButton_FilenameTemplateMoveTop.setObjectName("toolButton_FilenameTemplateMoveTop")
        self.verticalLayout.addWidget(self.toolButton_FilenameTemplateMoveTop)
        self.toolButton_FilenameTemplateUp = QtWidgets.QToolButton(self.groupBox_FilenameTemplates)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/move_up_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_FilenameTemplateUp.setIcon(icon4)
        self.toolButton_FilenameTemplateUp.setAutoRepeat(True)
        self.toolButton_FilenameTemplateUp.setAutoRepeatInterval(200)
        self.toolButton_FilenameTemplateUp.setObjectName("toolButton_FilenameTemplateUp")
        self.verticalLayout.addWidget(self.toolButton_FilenameTemplateUp)
        self.toolButton_FilenameTemplateMoveDown = QtWidgets.QToolButton(self.groupBox_FilenameTemplates)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/move_down_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_FilenameTemplateMoveDown.setIcon(icon5)
        self.toolButton_FilenameTemplateMoveDown.setAutoRepeat(True)
        self.toolButton_FilenameTemplateMoveDown.setAutoRepeatInterval(200)
        self.toolButton_FilenameTemplateMoveDown.setObjectName("toolButton_FilenameTemplateMoveDown")
        self.verticalLayout.addWidget(self.toolButton_FilenameTemplateMoveDown)
        self.toolButton_FilenameTemplateMoveBottom = QtWidgets.QToolButton(self.groupBox_FilenameTemplates)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/move_bottom_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_FilenameTemplateMoveBottom.setIcon(icon6)
        self.toolButton_FilenameTemplateMoveBottom.setObjectName("toolButton_FilenameTemplateMoveBottom")
        self.verticalLayout.addWidget(self.toolButton_FilenameTemplateMoveBottom)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_FilenameTemplates)
        self.groupBox_FilenameCharacterReplacement = QtWidgets.QGroupBox(self.tab_Filename)
        self.groupBox_FilenameCharacterReplacement.setObjectName("groupBox_FilenameCharacterReplacement")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_FilenameCharacterReplacement)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_FilenameCharacterReplace = QtWidgets.QCheckBox(self.groupBox_FilenameCharacterReplacement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_FilenameCharacterReplace.sizePolicy().hasHeightForWidth())
        self.checkBox_FilenameCharacterReplace.setSizePolicy(sizePolicy)
        self.checkBox_FilenameCharacterReplace.setObjectName("checkBox_FilenameCharacterReplace")
        self.gridLayout_6.addWidget(self.checkBox_FilenameCharacterReplace, 0, 0, 1, 2)
        self.lineEdit_FilenameCharacterReplaceWith = QtWidgets.QLineEdit(self.groupBox_FilenameCharacterReplacement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_FilenameCharacterReplaceWith.sizePolicy().hasHeightForWidth())
        self.lineEdit_FilenameCharacterReplaceWith.setSizePolicy(sizePolicy)
        self.lineEdit_FilenameCharacterReplaceWith.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_FilenameCharacterReplaceWith.setMaxLength(1)
        self.lineEdit_FilenameCharacterReplaceWith.setObjectName("lineEdit_FilenameCharacterReplaceWith")
        self.gridLayout_6.addWidget(self.lineEdit_FilenameCharacterReplaceWith, 0, 2, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 4, 1, 1)
        self.label_FilenameCharacterToReplace = QtWidgets.QLabel(self.groupBox_FilenameCharacterReplacement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FilenameCharacterToReplace.sizePolicy().hasHeightForWidth())
        self.label_FilenameCharacterToReplace.setSizePolicy(sizePolicy)
        self.label_FilenameCharacterToReplace.setObjectName("label_FilenameCharacterToReplace")
        self.gridLayout_6.addWidget(self.label_FilenameCharacterToReplace, 1, 0, 1, 1)
        self.lineEdit_FilenameCharactersToReplace = QtWidgets.QLineEdit(self.groupBox_FilenameCharacterReplacement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_FilenameCharactersToReplace.sizePolicy().hasHeightForWidth())
        self.lineEdit_FilenameCharactersToReplace.setSizePolicy(sizePolicy)
        self.lineEdit_FilenameCharactersToReplace.setObjectName("lineEdit_FilenameCharactersToReplace")
        self.gridLayout_6.addWidget(self.lineEdit_FilenameCharactersToReplace, 1, 1, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 3, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_FilenameCharacterReplacement)
        self.tabWidget.addTab(self.tab_Filename, "")
        self.tab_Presets = QtWidgets.QWidget()
        self.tab_Presets.setObjectName("tab_Presets")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_Presets)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_2 = QtWidgets.QFrame(self.tab_Presets)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.listWidget_Presets = QtWidgets.QListWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_Presets.sizePolicy().hasHeightForWidth())
        self.listWidget_Presets.setSizePolicy(sizePolicy)
        self.listWidget_Presets.setMinimumSize(QtCore.QSize(150, 0))
        self.listWidget_Presets.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidget_Presets.setObjectName("listWidget_Presets")
        self.horizontalLayout_6.addWidget(self.listWidget_Presets)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.toolButton_PresetAdd = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_PresetAdd.setIcon(icon)
        self.toolButton_PresetAdd.setObjectName("toolButton_PresetAdd")
        self.verticalLayout_8.addWidget(self.toolButton_PresetAdd)
        self.toolButton_PresetCopy = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_PresetCopy.setIcon(icon1)
        self.toolButton_PresetCopy.setObjectName("toolButton_PresetCopy")
        self.verticalLayout_8.addWidget(self.toolButton_PresetCopy)
        self.toolButton_PresetDelete = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_PresetDelete.setIcon(icon2)
        self.toolButton_PresetDelete.setObjectName("toolButton_PresetDelete")
        self.verticalLayout_8.addWidget(self.toolButton_PresetDelete)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem5)
        self.toolButton_PresetMoveTop = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_PresetMoveTop.setIcon(icon3)
        self.toolButton_PresetMoveTop.setObjectName("toolButton_PresetMoveTop")
        self.verticalLayout_8.addWidget(self.toolButton_PresetMoveTop)
        self.toolButton_PresetUp = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_PresetUp.setIcon(icon4)
        self.toolButton_PresetUp.setAutoRepeat(True)
        self.toolButton_PresetUp.setAutoRepeatInterval(200)
        self.toolButton_PresetUp.setObjectName("toolButton_PresetUp")
        self.verticalLayout_8.addWidget(self.toolButton_PresetUp)
        self.toolButton_PresetMoveDown = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_PresetMoveDown.setIcon(icon5)
        self.toolButton_PresetMoveDown.setAutoRepeat(True)
        self.toolButton_PresetMoveDown.setAutoRepeatInterval(200)
        self.toolButton_PresetMoveDown.setObjectName("toolButton_PresetMoveDown")
        self.verticalLayout_8.addWidget(self.toolButton_PresetMoveDown)
        self.toolButton_PresetMoveBottom = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_PresetMoveBottom.setIcon(icon6)
        self.toolButton_PresetMoveBottom.setObjectName("toolButton_PresetMoveBottom")
        self.verticalLayout_8.addWidget(self.toolButton_PresetMoveBottom)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.gridLayout_12.addWidget(self.frame_2, 0, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_PresetDetails = QtWidgets.QGroupBox(self.tab_Presets)
        self.groupBox_PresetDetails.setObjectName("groupBox_PresetDetails")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_PresetDetails)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_PresetsTag = QtWidgets.QLabel(self.groupBox_PresetDetails)
        self.label_PresetsTag.setObjectName("label_PresetsTag")
        self.gridLayout_11.addWidget(self.label_PresetsTag, 0, 0, 1, 1)
        self.lineEdit_PresetTag = QtWidgets.QLineEdit(self.groupBox_PresetDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_PresetTag.sizePolicy().hasHeightForWidth())
        self.lineEdit_PresetTag.setSizePolicy(sizePolicy)
        self.lineEdit_PresetTag.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_PresetTag.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_PresetTag.setObjectName("lineEdit_PresetTag")
        self.gridLayout_11.addWidget(self.lineEdit_PresetTag, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(195, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem7, 0, 2, 1, 1)
        self.label_PresetSettings = QtWidgets.QLabel(self.groupBox_PresetDetails)
        self.label_PresetSettings.setObjectName("label_PresetSettings")
        self.gridLayout_11.addWidget(self.label_PresetSettings, 1, 0, 1, 2)
        self.plainTextEdit_PresetSettings = QtWidgets.QPlainTextEdit(self.groupBox_PresetDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_PresetSettings.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_PresetSettings.setSizePolicy(sizePolicy)
        self.plainTextEdit_PresetSettings.setTabChangesFocus(True)
        self.plainTextEdit_PresetSettings.setObjectName("plainTextEdit_PresetSettings")
        self.gridLayout_11.addWidget(self.plainTextEdit_PresetSettings, 2, 0, 1, 3)
        self.verticalLayout_9.addWidget(self.groupBox_PresetDetails)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.gridLayout_12.addLayout(self.verticalLayout_9, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_Presets, "")
        self.tab_Mixdown = QtWidgets.QWidget()
        self.tab_Mixdown.setObjectName("tab_Mixdown")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_Mixdown)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.tab_Mixdown)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget_Mixdowns = QtWidgets.QListWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_Mixdowns.sizePolicy().hasHeightForWidth())
        self.listWidget_Mixdowns.setSizePolicy(sizePolicy)
        self.listWidget_Mixdowns.setMinimumSize(QtCore.QSize(150, 0))
        self.listWidget_Mixdowns.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidget_Mixdowns.setObjectName("listWidget_Mixdowns")
        self.horizontalLayout_4.addWidget(self.listWidget_Mixdowns)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolButton_MixdownAdd = QtWidgets.QToolButton(self.frame)
        self.toolButton_MixdownAdd.setIcon(icon)
        self.toolButton_MixdownAdd.setObjectName("toolButton_MixdownAdd")
        self.verticalLayout_6.addWidget(self.toolButton_MixdownAdd)
        self.toolButton_MixdownCopy = QtWidgets.QToolButton(self.frame)
        self.toolButton_MixdownCopy.setIcon(icon1)
        self.toolButton_MixdownCopy.setObjectName("toolButton_MixdownCopy")
        self.verticalLayout_6.addWidget(self.toolButton_MixdownCopy)
        self.toolButton_MixdownDelete = QtWidgets.QToolButton(self.frame)
        self.toolButton_MixdownDelete.setIcon(icon2)
        self.toolButton_MixdownDelete.setObjectName("toolButton_MixdownDelete")
        self.verticalLayout_6.addWidget(self.toolButton_MixdownDelete)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem9)
        self.toolButton_MixdownMoveTop = QtWidgets.QToolButton(self.frame)
        self.toolButton_MixdownMoveTop.setIcon(icon3)
        self.toolButton_MixdownMoveTop.setObjectName("toolButton_MixdownMoveTop")
        self.verticalLayout_6.addWidget(self.toolButton_MixdownMoveTop)
        self.toolButton_MixdownUp = QtWidgets.QToolButton(self.frame)
        self.toolButton_MixdownUp.setIcon(icon4)
        self.toolButton_MixdownUp.setAutoRepeat(True)
        self.toolButton_MixdownUp.setAutoRepeatInterval(200)
        self.toolButton_MixdownUp.setObjectName("toolButton_MixdownUp")
        self.verticalLayout_6.addWidget(self.toolButton_MixdownUp)
        self.toolButton_MixdownMoveDown = QtWidgets.QToolButton(self.frame)
        self.toolButton_MixdownMoveDown.setIcon(icon5)
        self.toolButton_MixdownMoveDown.setAutoRepeat(True)
        self.toolButton_MixdownMoveDown.setAutoRepeatInterval(200)
        self.toolButton_MixdownMoveDown.setObjectName("toolButton_MixdownMoveDown")
        self.verticalLayout_6.addWidget(self.toolButton_MixdownMoveDown)
        self.toolButton_MixdownMoveBottom = QtWidgets.QToolButton(self.frame)
        self.toolButton_MixdownMoveBottom.setIcon(icon6)
        self.toolButton_MixdownMoveBottom.setObjectName("toolButton_MixdownMoveBottom")
        self.verticalLayout_6.addWidget(self.toolButton_MixdownMoveBottom)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5.addWidget(self.frame)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_MixdownDetails = QtWidgets.QGroupBox(self.tab_Mixdown)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_MixdownDetails.sizePolicy().hasHeightForWidth())
        self.groupBox_MixdownDetails.setSizePolicy(sizePolicy)
        self.groupBox_MixdownDetails.setObjectName("groupBox_MixdownDetails")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_MixdownDetails)
        self.formLayout.setObjectName("formLayout")
        self.label_MixdownTag = QtWidgets.QLabel(self.groupBox_MixdownDetails)
        self.label_MixdownTag.setObjectName("label_MixdownTag")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_MixdownTag)
        self.lineEdit_MixdownTag = QtWidgets.QLineEdit(self.groupBox_MixdownDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MixdownTag.sizePolicy().hasHeightForWidth())
        self.lineEdit_MixdownTag.setSizePolicy(sizePolicy)
        self.lineEdit_MixdownTag.setObjectName("lineEdit_MixdownTag")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_MixdownTag)
        self.label_MixdownEncoder = QtWidgets.QLabel(self.groupBox_MixdownDetails)
        self.label_MixdownEncoder.setObjectName("label_MixdownEncoder")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_MixdownEncoder)
        self.lineEdit_MixdownEncoder = QtWidgets.QLineEdit(self.groupBox_MixdownDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MixdownEncoder.sizePolicy().hasHeightForWidth())
        self.lineEdit_MixdownEncoder.setSizePolicy(sizePolicy)
        self.lineEdit_MixdownEncoder.setObjectName("lineEdit_MixdownEncoder")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_MixdownEncoder)
        self.label_MixdownMixdown = QtWidgets.QLabel(self.groupBox_MixdownDetails)
        self.label_MixdownMixdown.setObjectName("label_MixdownMixdown")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_MixdownMixdown)
        self.lineEdit_MixdownMixdown = QtWidgets.QLineEdit(self.groupBox_MixdownDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MixdownMixdown.sizePolicy().hasHeightForWidth())
        self.lineEdit_MixdownMixdown.setSizePolicy(sizePolicy)
        self.lineEdit_MixdownMixdown.setObjectName("lineEdit_MixdownMixdown")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_MixdownMixdown)
        self.label_MixdownBitrate = QtWidgets.QLabel(self.groupBox_MixdownDetails)
        self.label_MixdownBitrate.setObjectName("label_MixdownBitrate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_MixdownBitrate)
        self.lineEdit_MixdownBitrate = QtWidgets.QLineEdit(self.groupBox_MixdownDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MixdownBitrate.sizePolicy().hasHeightForWidth())
        self.lineEdit_MixdownBitrate.setSizePolicy(sizePolicy)
        self.lineEdit_MixdownBitrate.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_MixdownBitrate.setObjectName("lineEdit_MixdownBitrate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_MixdownBitrate)
        self.label_MixdownSampleRate = QtWidgets.QLabel(self.groupBox_MixdownDetails)
        self.label_MixdownSampleRate.setObjectName("label_MixdownSampleRate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_MixdownSampleRate)
        self.lineEdit_MixdownSampleRate = QtWidgets.QLineEdit(self.groupBox_MixdownDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MixdownSampleRate.sizePolicy().hasHeightForWidth())
        self.lineEdit_MixdownSampleRate.setSizePolicy(sizePolicy)
        self.lineEdit_MixdownSampleRate.setObjectName("lineEdit_MixdownSampleRate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_MixdownSampleRate)
        self.label_MixdonwDynamicRangeCompression = QtWidgets.QLabel(self.groupBox_MixdownDetails)
        self.label_MixdonwDynamicRangeCompression.setObjectName("label_MixdonwDynamicRangeCompression")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_MixdonwDynamicRangeCompression)
        self.lineEdit_MixdownDynamicRangeCompression = QtWidgets.QLineEdit(self.groupBox_MixdownDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MixdownDynamicRangeCompression.sizePolicy().hasHeightForWidth())
        self.lineEdit_MixdownDynamicRangeCompression.setSizePolicy(sizePolicy)
        self.lineEdit_MixdownDynamicRangeCompression.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_MixdownDynamicRangeCompression.setObjectName("lineEdit_MixdownDynamicRangeCompression")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_MixdownDynamicRangeCompression)
        self.label_MixdownGain = QtWidgets.QLabel(self.groupBox_MixdownDetails)
        self.label_MixdownGain.setObjectName("label_MixdownGain")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_MixdownGain)
        self.lineEdit_MixdownGain = QtWidgets.QLineEdit(self.groupBox_MixdownDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MixdownGain.sizePolicy().hasHeightForWidth())
        self.lineEdit_MixdownGain.setSizePolicy(sizePolicy)
        self.lineEdit_MixdownGain.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_MixdownGain.setObjectName("lineEdit_MixdownGain")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_MixdownGain)
        self.verticalLayout_7.addWidget(self.groupBox_MixdownDetails)
        spacerItem11 = QtWidgets.QSpacerItem(20, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem11)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        spacerItem12 = QtWidgets.QSpacerItem(92, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.tabWidget.addTab(self.tab_Mixdown, "")
        self.tab_DiscSession = QtWidgets.QWidget()
        self.tab_DiscSession.setObjectName("tab_DiscSession")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_DiscSession)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_DiscSessionAutomaticSessions = QtWidgets.QGroupBox(self.tab_DiscSession)
        self.groupBox_DiscSessionAutomaticSessions.setObjectName("groupBox_DiscSessionAutomaticSessions")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_DiscSessionAutomaticSessions)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.checkBox_DiscSessionsAutoDiscSessions = QtWidgets.QCheckBox(self.groupBox_DiscSessionAutomaticSessions)
        self.checkBox_DiscSessionsAutoDiscSessions.setObjectName("checkBox_DiscSessionsAutoDiscSessions")
        self.gridLayout_13.addWidget(self.checkBox_DiscSessionsAutoDiscSessions, 0, 0, 1, 2)
        self.label_DiscSessionAutomaticSessionFolder = QtWidgets.QLabel(self.groupBox_DiscSessionAutomaticSessions)
        self.label_DiscSessionAutomaticSessionFolder.setObjectName("label_DiscSessionAutomaticSessionFolder")
        self.gridLayout_13.addWidget(self.label_DiscSessionAutomaticSessionFolder, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_DiscSessionAutomaticSessionsFolder = QtWidgets.QLineEdit(self.groupBox_DiscSessionAutomaticSessions)
        self.lineEdit_DiscSessionAutomaticSessionsFolder.setClearButtonEnabled(True)
        self.lineEdit_DiscSessionAutomaticSessionsFolder.setObjectName("lineEdit_DiscSessionAutomaticSessionsFolder")
        self.horizontalLayout_7.addWidget(self.lineEdit_DiscSessionAutomaticSessionsFolder)
        self.pushButton_BrowseAutomaticSessionFolder = QtWidgets.QPushButton(self.groupBox_DiscSessionAutomaticSessions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_BrowseAutomaticSessionFolder.sizePolicy().hasHeightForWidth())
        self.pushButton_BrowseAutomaticSessionFolder.setSizePolicy(sizePolicy)
        self.pushButton_BrowseAutomaticSessionFolder.setObjectName("pushButton_BrowseAutomaticSessionFolder")
        self.horizontalLayout_7.addWidget(self.pushButton_BrowseAutomaticSessionFolder)
        self.gridLayout_13.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.label_DiscSessionAutomaticFilenamePrefix = QtWidgets.QLabel(self.groupBox_DiscSessionAutomaticSessions)
        self.label_DiscSessionAutomaticFilenamePrefix.setObjectName("label_DiscSessionAutomaticFilenamePrefix")
        self.gridLayout_13.addWidget(self.label_DiscSessionAutomaticFilenamePrefix, 2, 0, 1, 1)
        self.lineEdit_DiscSessionAutomaticFilenamePrefix = QtWidgets.QLineEdit(self.groupBox_DiscSessionAutomaticSessions)
        self.lineEdit_DiscSessionAutomaticFilenamePrefix.setClearButtonEnabled(True)
        self.lineEdit_DiscSessionAutomaticFilenamePrefix.setObjectName("lineEdit_DiscSessionAutomaticFilenamePrefix")
        self.gridLayout_13.addWidget(self.lineEdit_DiscSessionAutomaticFilenamePrefix, 2, 1, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_DiscSessionAutomaticSessions, 0, 0, 1, 1)
        self.groupBoxDiscSessionLoadSession = QtWidgets.QGroupBox(self.tab_DiscSession)
        self.groupBoxDiscSessionLoadSession.setObjectName("groupBoxDiscSessionLoadSession")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBoxDiscSessionLoadSession)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.checkBox_LoadSessionKeepPosition = QtWidgets.QCheckBox(self.groupBoxDiscSessionLoadSession)
        self.checkBox_LoadSessionKeepPosition.setObjectName("checkBox_LoadSessionKeepPosition")
        self.verticalLayout_10.addWidget(self.checkBox_LoadSessionKeepPosition)
        self.checkBoxLoadSessionKeepSize = QtWidgets.QCheckBox(self.groupBoxDiscSessionLoadSession)
        self.checkBoxLoadSessionKeepSize.setObjectName("checkBoxLoadSessionKeepSize")
        self.verticalLayout_10.addWidget(self.checkBoxLoadSessionKeepSize)
        self.checkBoxLoadSessionKeepDestination = QtWidgets.QCheckBox(self.groupBoxDiscSessionLoadSession)
        self.checkBoxLoadSessionKeepDestination.setObjectName("checkBoxLoadSessionKeepDestination")
        self.verticalLayout_10.addWidget(self.checkBoxLoadSessionKeepDestination)
        self.gridLayout_14.addWidget(self.groupBoxDiscSessionLoadSession, 1, 0, 1, 1)
        self.groupBox_NewSource = QtWidgets.QGroupBox(self.tab_DiscSession)
        self.groupBox_NewSource.setObjectName("groupBox_NewSource")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_NewSource)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox_SelectFirstMask = QtWidgets.QCheckBox(self.groupBox_NewSource)
        self.checkBox_SelectFirstMask.setObjectName("checkBox_SelectFirstMask")
        self.gridLayout_5.addWidget(self.checkBox_SelectFirstMask, 0, 0, 1, 2)
        self.checkBox_SelectFirstPreset = QtWidgets.QCheckBox(self.groupBox_NewSource)
        self.checkBox_SelectFirstPreset.setObjectName("checkBox_SelectFirstPreset")
        self.gridLayout_5.addWidget(self.checkBox_SelectFirstPreset, 1, 0, 1, 2)
        self.checkBox_DefaultDestination = QtWidgets.QCheckBox(self.groupBox_NewSource)
        self.checkBox_DefaultDestination.setObjectName("checkBox_DefaultDestination")
        self.gridLayout_5.addWidget(self.checkBox_DefaultDestination, 2, 0, 1, 1)
        self.lineEdit_DefaultDestination = QtWidgets.QLineEdit(self.groupBox_NewSource)
        self.lineEdit_DefaultDestination.setClearButtonEnabled(True)
        self.lineEdit_DefaultDestination.setObjectName("lineEdit_DefaultDestination")
        self.gridLayout_5.addWidget(self.lineEdit_DefaultDestination, 2, 1, 1, 1)
        self.pushButton_BrowseDefaultDestination = QtWidgets.QPushButton(self.groupBox_NewSource)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_BrowseDefaultDestination.sizePolicy().hasHeightForWidth())
        self.pushButton_BrowseDefaultDestination.setSizePolicy(sizePolicy)
        self.pushButton_BrowseDefaultDestination.setObjectName("pushButton_BrowseDefaultDestination")
        self.gridLayout_5.addWidget(self.pushButton_BrowseDefaultDestination, 2, 2, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_NewSource, 2, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem13, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_DiscSession, "")
        self.tab_Auto1 = QtWidgets.QWidget()
        self.tab_Auto1.setObjectName("tab_Auto1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_Auto1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_AutoTitles = QtWidgets.QGroupBox(self.tab_Auto1)
        self.groupBox_AutoTitles.setObjectName("groupBox_AutoTitles")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_AutoTitles)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_AutoSelectLongestTitle = QtWidgets.QCheckBox(self.groupBox_AutoTitles)
        self.checkBox_AutoSelectLongestTitle.setObjectName("checkBox_AutoSelectLongestTitle")
        self.gridLayout_7.addWidget(self.checkBox_AutoSelectLongestTitle, 0, 0, 1, 3)
        self.label_AutoShortTitleSeconds_1 = QtWidgets.QLabel(self.groupBox_AutoTitles)
        self.label_AutoShortTitleSeconds_1.setObjectName("label_AutoShortTitleSeconds_1")
        self.gridLayout_7.addWidget(self.label_AutoShortTitleSeconds_1, 1, 0, 1, 1)
        self.spinBox_AutoShortTitleSeconds = QtWidgets.QSpinBox(self.groupBox_AutoTitles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_AutoShortTitleSeconds.sizePolicy().hasHeightForWidth())
        self.spinBox_AutoShortTitleSeconds.setSizePolicy(sizePolicy)
        self.spinBox_AutoShortTitleSeconds.setSuffix("")
        self.spinBox_AutoShortTitleSeconds.setMinimum(1)
        self.spinBox_AutoShortTitleSeconds.setMaximum(59)
        self.spinBox_AutoShortTitleSeconds.setProperty("value", 30)
        self.spinBox_AutoShortTitleSeconds.setObjectName("spinBox_AutoShortTitleSeconds")
        self.gridLayout_7.addWidget(self.spinBox_AutoShortTitleSeconds, 1, 1, 1, 1)
        self.label_AutoShortTitleSeconds_2 = QtWidgets.QLabel(self.groupBox_AutoTitles)
        self.label_AutoShortTitleSeconds_2.setIndent(0)
        self.label_AutoShortTitleSeconds_2.setObjectName("label_AutoShortTitleSeconds_2")
        self.gridLayout_7.addWidget(self.label_AutoShortTitleSeconds_2, 1, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(245, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem14, 1, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_AutoTitles)
        self.groupBox_AutoAudioTracks = QtWidgets.QGroupBox(self.tab_Auto1)
        self.groupBox_AutoAudioTracks.setObjectName("groupBox_AutoAudioTracks")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_AutoAudioTracks)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox_AutoAudioPreferredLanguage = QtWidgets.QCheckBox(self.groupBox_AutoAudioTracks)
        self.checkBox_AutoAudioPreferredLanguage.setObjectName("checkBox_AutoAudioPreferredLanguage")
        self.gridLayout_8.addWidget(self.checkBox_AutoAudioPreferredLanguage, 0, 0, 1, 1)
        self.lineEdit_AutoAudioPreferredLanguage = QtWidgets.QLineEdit(self.groupBox_AutoAudioTracks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_AutoAudioPreferredLanguage.sizePolicy().hasHeightForWidth())
        self.lineEdit_AutoAudioPreferredLanguage.setSizePolicy(sizePolicy)
        self.lineEdit_AutoAudioPreferredLanguage.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_AutoAudioPreferredLanguage.setObjectName("lineEdit_AutoAudioPreferredLanguage")
        self.gridLayout_8.addWidget(self.lineEdit_AutoAudioPreferredLanguage, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(314, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem15, 0, 2, 1, 1)
        self.checkBox_AutoAudioSelect51 = QtWidgets.QCheckBox(self.groupBox_AutoAudioTracks)
        self.checkBox_AutoAudioSelect51.setObjectName("checkBox_AutoAudioSelect51")
        self.gridLayout_8.addWidget(self.checkBox_AutoAudioSelect51, 1, 0, 1, 3)
        self.checkBox_AutoAudioSelectDTS = QtWidgets.QCheckBox(self.groupBox_AutoAudioTracks)
        self.checkBox_AutoAudioSelectDTS.setObjectName("checkBox_AutoAudioSelectDTS")
        self.gridLayout_8.addWidget(self.checkBox_AutoAudioSelectDTS, 2, 0, 1, 3)
        self.checkBox_AutoAudioFallback = QtWidgets.QCheckBox(self.groupBox_AutoAudioTracks)
        self.checkBox_AutoAudioFallback.setObjectName("checkBox_AutoAudioFallback")
        self.gridLayout_8.addWidget(self.checkBox_AutoAudioFallback, 3, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.groupBox_AutoAudioTracks)
        self.groupBox_AutoSubtitles = QtWidgets.QGroupBox(self.tab_Auto1)
        self.groupBox_AutoSubtitles.setObjectName("groupBox_AutoSubtitles")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_AutoSubtitles)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.checkBox_AutoSubtitlePreferredLanguage = QtWidgets.QCheckBox(self.groupBox_AutoSubtitles)
        self.checkBox_AutoSubtitlePreferredLanguage.setObjectName("checkBox_AutoSubtitlePreferredLanguage")
        self.gridLayout_9.addWidget(self.checkBox_AutoSubtitlePreferredLanguage, 0, 0, 1, 1)
        self.lineEdit_AutoSubtitlePreferredLanguage = QtWidgets.QLineEdit(self.groupBox_AutoSubtitles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_AutoSubtitlePreferredLanguage.sizePolicy().hasHeightForWidth())
        self.lineEdit_AutoSubtitlePreferredLanguage.setSizePolicy(sizePolicy)
        self.lineEdit_AutoSubtitlePreferredLanguage.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_AutoSubtitlePreferredLanguage.setObjectName("lineEdit_AutoSubtitlePreferredLanguage")
        self.gridLayout_9.addWidget(self.lineEdit_AutoSubtitlePreferredLanguage, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(303, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem16, 0, 2, 1, 1)
        self.checkBox_AutoSubtitleFirstTrack = QtWidgets.QCheckBox(self.groupBox_AutoSubtitles)
        self.checkBox_AutoSubtitleFirstTrack.setObjectName("checkBox_AutoSubtitleFirstTrack")
        self.gridLayout_9.addWidget(self.checkBox_AutoSubtitleFirstTrack, 1, 0, 1, 3)
        self.checkBox_AutoSubtitleBurnIn = QtWidgets.QCheckBox(self.groupBox_AutoSubtitles)
        self.checkBox_AutoSubtitleBurnIn.setObjectName("checkBox_AutoSubtitleBurnIn")
        self.gridLayout_9.addWidget(self.checkBox_AutoSubtitleBurnIn, 2, 0, 1, 1)
        self.checkBox_AutoSubtitleDefault = QtWidgets.QCheckBox(self.groupBox_AutoSubtitles)
        self.checkBox_AutoSubtitleDefault.setObjectName("checkBox_AutoSubtitleDefault")
        self.gridLayout_9.addWidget(self.checkBox_AutoSubtitleDefault, 3, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.groupBox_AutoSubtitles)
        spacerItem17 = QtWidgets.QSpacerItem(20, 26, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem17)
        self.tabWidget.addTab(self.tab_Auto1, "")
        self.tab_Auto2 = QtWidgets.QWidget()
        self.tab_Auto2.setObjectName("tab_Auto2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_Auto2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_AutoAudioMixdowns = QtWidgets.QGroupBox(self.tab_Auto2)
        self.groupBox_AutoAudioMixdowns.setObjectName("groupBox_AutoAudioMixdowns")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_AutoAudioMixdowns)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_AutoAudioMixdownPrimary = QtWidgets.QLabel(self.groupBox_AutoAudioMixdowns)
        self.label_AutoAudioMixdownPrimary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_AutoAudioMixdownPrimary.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AutoAudioMixdownPrimary.setObjectName("label_AutoAudioMixdownPrimary")
        self.gridLayout_10.addWidget(self.label_AutoAudioMixdownPrimary, 0, 1, 1, 1)
        self.label_AutoAudioMixdownSecondary = QtWidgets.QLabel(self.groupBox_AutoAudioMixdowns)
        self.label_AutoAudioMixdownSecondary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_AutoAudioMixdownSecondary.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AutoAudioMixdownSecondary.setObjectName("label_AutoAudioMixdownSecondary")
        self.gridLayout_10.addWidget(self.label_AutoAudioMixdownSecondary, 0, 2, 1, 1)
        self.label_AutoAudioMidownAC3_51 = QtWidgets.QLabel(self.groupBox_AutoAudioMixdowns)
        self.label_AutoAudioMidownAC3_51.setObjectName("label_AutoAudioMidownAC3_51")
        self.gridLayout_10.addWidget(self.label_AutoAudioMidownAC3_51, 1, 0, 1, 1)
        self.comboBox_AutoAudioMixdownAC3_51_Primary = QtWidgets.QComboBox(self.groupBox_AutoAudioMixdowns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_AutoAudioMixdownAC3_51_Primary.sizePolicy().hasHeightForWidth())
        self.comboBox_AutoAudioMixdownAC3_51_Primary.setSizePolicy(sizePolicy)
        self.comboBox_AutoAudioMixdownAC3_51_Primary.setMinimumSize(QtCore.QSize(125, 0))
        self.comboBox_AutoAudioMixdownAC3_51_Primary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.comboBox_AutoAudioMixdownAC3_51_Primary.setObjectName("comboBox_AutoAudioMixdownAC3_51_Primary")
        self.gridLayout_10.addWidget(self.comboBox_AutoAudioMixdownAC3_51_Primary, 1, 1, 1, 1)
        self.comboBox_AutoAudioMixdownAC3_51_Secondary = QtWidgets.QComboBox(self.groupBox_AutoAudioMixdowns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_AutoAudioMixdownAC3_51_Secondary.sizePolicy().hasHeightForWidth())
        self.comboBox_AutoAudioMixdownAC3_51_Secondary.setSizePolicy(sizePolicy)
        self.comboBox_AutoAudioMixdownAC3_51_Secondary.setMinimumSize(QtCore.QSize(125, 0))
        self.comboBox_AutoAudioMixdownAC3_51_Secondary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.comboBox_AutoAudioMixdownAC3_51_Secondary.setObjectName("comboBox_AutoAudioMixdownAC3_51_Secondary")
        self.gridLayout_10.addWidget(self.comboBox_AutoAudioMixdownAC3_51_Secondary, 1, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem18, 1, 3, 1, 1)
        self.label_AutoAudioMixdownDTS = QtWidgets.QLabel(self.groupBox_AutoAudioMixdowns)
        self.label_AutoAudioMixdownDTS.setObjectName("label_AutoAudioMixdownDTS")
        self.gridLayout_10.addWidget(self.label_AutoAudioMixdownDTS, 2, 0, 1, 1)
        self.comboBox_AutoAudioMixdownDTS_Primary = QtWidgets.QComboBox(self.groupBox_AutoAudioMixdowns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_AutoAudioMixdownDTS_Primary.sizePolicy().hasHeightForWidth())
        self.comboBox_AutoAudioMixdownDTS_Primary.setSizePolicy(sizePolicy)
        self.comboBox_AutoAudioMixdownDTS_Primary.setMinimumSize(QtCore.QSize(125, 0))
        self.comboBox_AutoAudioMixdownDTS_Primary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.comboBox_AutoAudioMixdownDTS_Primary.setObjectName("comboBox_AutoAudioMixdownDTS_Primary")
        self.gridLayout_10.addWidget(self.comboBox_AutoAudioMixdownDTS_Primary, 2, 1, 1, 1)
        self.comboBox_AutoAudioMixdownDTS_Secondary = QtWidgets.QComboBox(self.groupBox_AutoAudioMixdowns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_AutoAudioMixdownDTS_Secondary.sizePolicy().hasHeightForWidth())
        self.comboBox_AutoAudioMixdownDTS_Secondary.setSizePolicy(sizePolicy)
        self.comboBox_AutoAudioMixdownDTS_Secondary.setMinimumSize(QtCore.QSize(125, 0))
        self.comboBox_AutoAudioMixdownDTS_Secondary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.comboBox_AutoAudioMixdownDTS_Secondary.setObjectName("comboBox_AutoAudioMixdownDTS_Secondary")
        self.gridLayout_10.addWidget(self.comboBox_AutoAudioMixdownDTS_Secondary, 2, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem19, 2, 3, 1, 1)
        self.label_AutoAudioMixdownDTSHD = QtWidgets.QLabel(self.groupBox_AutoAudioMixdowns)
        self.label_AutoAudioMixdownDTSHD.setObjectName("label_AutoAudioMixdownDTSHD")
        self.gridLayout_10.addWidget(self.label_AutoAudioMixdownDTSHD, 3, 0, 1, 1)
        self.comboBox_AutoAudioMixdownDTSHD_Primary = QtWidgets.QComboBox(self.groupBox_AutoAudioMixdowns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_AutoAudioMixdownDTSHD_Primary.sizePolicy().hasHeightForWidth())
        self.comboBox_AutoAudioMixdownDTSHD_Primary.setSizePolicy(sizePolicy)
        self.comboBox_AutoAudioMixdownDTSHD_Primary.setMinimumSize(QtCore.QSize(125, 0))
        self.comboBox_AutoAudioMixdownDTSHD_Primary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.comboBox_AutoAudioMixdownDTSHD_Primary.setObjectName("comboBox_AutoAudioMixdownDTSHD_Primary")
        self.gridLayout_10.addWidget(self.comboBox_AutoAudioMixdownDTSHD_Primary, 3, 1, 1, 1)
        self.comboBox_AutoAudioMixdownDTSHD_Secondary = QtWidgets.QComboBox(self.groupBox_AutoAudioMixdowns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_AutoAudioMixdownDTSHD_Secondary.sizePolicy().hasHeightForWidth())
        self.comboBox_AutoAudioMixdownDTSHD_Secondary.setSizePolicy(sizePolicy)
        self.comboBox_AutoAudioMixdownDTSHD_Secondary.setMinimumSize(QtCore.QSize(125, 0))
        self.comboBox_AutoAudioMixdownDTSHD_Secondary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.comboBox_AutoAudioMixdownDTSHD_Secondary.setObjectName("comboBox_AutoAudioMixdownDTSHD_Secondary")
        self.gridLayout_10.addWidget(self.comboBox_AutoAudioMixdownDTSHD_Secondary, 3, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem20, 3, 3, 1, 1)
        self.label_AutoAudioMixdownAC3 = QtWidgets.QLabel(self.groupBox_AutoAudioMixdowns)
        self.label_AutoAudioMixdownAC3.setObjectName("label_AutoAudioMixdownAC3")
        self.gridLayout_10.addWidget(self.label_AutoAudioMixdownAC3, 4, 0, 1, 1)
        self.comboBox_AutoAudioMixdownAC3_Primary = QtWidgets.QComboBox(self.groupBox_AutoAudioMixdowns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_AutoAudioMixdownAC3_Primary.sizePolicy().hasHeightForWidth())
        self.comboBox_AutoAudioMixdownAC3_Primary.setSizePolicy(sizePolicy)
        self.comboBox_AutoAudioMixdownAC3_Primary.setMinimumSize(QtCore.QSize(125, 0))
        self.comboBox_AutoAudioMixdownAC3_Primary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.comboBox_AutoAudioMixdownAC3_Primary.setObjectName("comboBox_AutoAudioMixdownAC3_Primary")
        self.gridLayout_10.addWidget(self.comboBox_AutoAudioMixdownAC3_Primary, 4, 1, 1, 1)
        self.comboBox_AutoAudioMixdownAC3_Secondary = QtWidgets.QComboBox(self.groupBox_AutoAudioMixdowns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_AutoAudioMixdownAC3_Secondary.sizePolicy().hasHeightForWidth())
        self.comboBox_AutoAudioMixdownAC3_Secondary.setSizePolicy(sizePolicy)
        self.comboBox_AutoAudioMixdownAC3_Secondary.setMinimumSize(QtCore.QSize(125, 0))
        self.comboBox_AutoAudioMixdownAC3_Secondary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.comboBox_AutoAudioMixdownAC3_Secondary.setObjectName("comboBox_AutoAudioMixdownAC3_Secondary")
        self.gridLayout_10.addWidget(self.comboBox_AutoAudioMixdownAC3_Secondary, 4, 2, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem21, 4, 3, 1, 1)
        self.label_AutoAudioMixdownDefault = QtWidgets.QLabel(self.groupBox_AutoAudioMixdowns)
        self.label_AutoAudioMixdownDefault.setObjectName("label_AutoAudioMixdownDefault")
        self.gridLayout_10.addWidget(self.label_AutoAudioMixdownDefault, 5, 0, 1, 1)
        self.comboBox_AutoAudioMixdownDefault_Primary = QtWidgets.QComboBox(self.groupBox_AutoAudioMixdowns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_AutoAudioMixdownDefault_Primary.sizePolicy().hasHeightForWidth())
        self.comboBox_AutoAudioMixdownDefault_Primary.setSizePolicy(sizePolicy)
        self.comboBox_AutoAudioMixdownDefault_Primary.setMinimumSize(QtCore.QSize(125, 0))
        self.comboBox_AutoAudioMixdownDefault_Primary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.comboBox_AutoAudioMixdownDefault_Primary.setObjectName("comboBox_AutoAudioMixdownDefault_Primary")
        self.gridLayout_10.addWidget(self.comboBox_AutoAudioMixdownDefault_Primary, 5, 1, 1, 1)
        self.comboBox_AutoAudioMixdownDefault_Secondary = QtWidgets.QComboBox(self.groupBox_AutoAudioMixdowns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_AutoAudioMixdownDefault_Secondary.sizePolicy().hasHeightForWidth())
        self.comboBox_AutoAudioMixdownDefault_Secondary.setSizePolicy(sizePolicy)
        self.comboBox_AutoAudioMixdownDefault_Secondary.setMinimumSize(QtCore.QSize(125, 0))
        self.comboBox_AutoAudioMixdownDefault_Secondary.setMaximumSize(QtCore.QSize(125, 16777215))
        self.comboBox_AutoAudioMixdownDefault_Secondary.setObjectName("comboBox_AutoAudioMixdownDefault_Secondary")
        self.gridLayout_10.addWidget(self.comboBox_AutoAudioMixdownDefault_Secondary, 5, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem22, 5, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_AutoAudioMixdowns)
        self.groupBox_AutoCrop = QtWidgets.QGroupBox(self.tab_Auto2)
        self.groupBox_AutoCrop.setObjectName("groupBox_AutoCrop")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_AutoCrop)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_AutoCropReset = QtWidgets.QCheckBox(self.groupBox_AutoCrop)
        self.checkBox_AutoCropReset.setObjectName("checkBox_AutoCropReset")
        self.verticalLayout_4.addWidget(self.checkBox_AutoCropReset)
        self.checkBox_AutoCropCopyLongestTitle = QtWidgets.QCheckBox(self.groupBox_AutoCrop)
        self.checkBox_AutoCropCopyLongestTitle.setObjectName("checkBox_AutoCropCopyLongestTitle")
        self.verticalLayout_4.addWidget(self.checkBox_AutoCropCopyLongestTitle)
        self.verticalLayout_5.addWidget(self.groupBox_AutoCrop)
        spacerItem23 = QtWidgets.QSpacerItem(20, 101, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem23)
        self.tabWidget.addTab(self.tab_Auto2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label_HandBrakeCLI.setBuddy(self.lineEdit_HandBrakeCLI)
        self.label_VLC.setBuddy(self.lineEdit_VLC)
        self.label_LogFile.setBuddy(self.lineEdit_LogFilename)
        self.label_FilenameCharacterToReplace.setBuddy(self.lineEdit_FilenameCharactersToReplace)
        self.label_PresetsTag.setBuddy(self.lineEdit_PresetTag)
        self.label_DiscSessionAutomaticSessionFolder.setBuddy(self.lineEdit_DiscSessionAutomaticSessionsFolder)
        self.label_DiscSessionAutomaticFilenamePrefix.setBuddy(self.lineEdit_DiscSessionAutomaticFilenamePrefix)
        self.label_AutoShortTitleSeconds_1.setBuddy(self.spinBox_AutoShortTitleSeconds)
        self.label_AutoShortTitleSeconds_2.setBuddy(self.spinBox_AutoShortTitleSeconds)

        self.retranslateUi(DialogPreferences)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(DialogPreferences.accept)
        self.buttonBox.rejected.connect(DialogPreferences.reject)
        self.checkBox_SetShortLastChapter.toggled['bool'].connect(self.lineEdit_ShortLastChapter.setEnabled)
        self.checkBox_FilenameCharacterReplace.toggled['bool'].connect(self.lineEdit_FilenameCharacterReplaceWith.setEnabled)
        self.checkBox_FilenameCharacterReplace.toggled['bool'].connect(self.lineEdit_FilenameCharactersToReplace.setEnabled)
        self.checkBox_AutoAudioPreferredLanguage.toggled['bool'].connect(self.lineEdit_AutoAudioPreferredLanguage.setEnabled)
        self.checkBox_AutoSubtitlePreferredLanguage.toggled['bool'].connect(self.lineEdit_AutoSubtitlePreferredLanguage.setEnabled)
        self.checkBox_DiscSessionsAutoDiscSessions.toggled['bool'].connect(self.lineEdit_DiscSessionAutomaticSessionsFolder.setEnabled)
        self.checkBox_DiscSessionsAutoDiscSessions.toggled['bool'].connect(self.lineEdit_DiscSessionAutomaticFilenamePrefix.setEnabled)
        self.checkBox_DiscSessionsAutoDiscSessions.toggled['bool'].connect(self.pushButton_BrowseAutomaticSessionFolder.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DialogPreferences)

    def retranslateUi(self, DialogPreferences):
        _translate = QtCore.QCoreApplication.translate
        DialogPreferences.setWindowTitle(_translate("DialogPreferences", "QtHEP Preferences"))
        self.groupBox_Executables.setTitle(_translate("DialogPreferences", "Executables"))
        self.label_HandBrakeCLI.setText(_translate("DialogPreferences", "HandBrakeCLI"))
        self.lineEdit_HandBrakeCLI.setPlaceholderText(_translate("DialogPreferences", "Path to HandBrakeCLI"))
        self.pushButton_BrowseHandBrakeCLI.setToolTip(_translate("DialogPreferences", "Find the location of the HandBrakeCLI executable"))
        self.pushButton_BrowseHandBrakeCLI.setText(_translate("DialogPreferences", "Browse"))
        self.label_VLC.setText(_translate("DialogPreferences", "VLC"))
        self.lineEdit_VLC.setPlaceholderText(_translate("DialogPreferences", "Path to VLC"))
        self.pushButton_BrowseVLC.setToolTip(_translate("DialogPreferences", "Find the location of the VLC executable."))
        self.pushButton_BrowseVLC.setText(_translate("DialogPreferences", "Browse"))
        self.groupBox_Logging.setTitle(_translate("DialogPreferences", "Logging"))
        self.checkBox_LogHandBrakeAnalysis.setText(_translate("DialogPreferences", "Log HandBrake analysis of source."))
        self.checkBox_LogHandBrakeTranscoding.setText(_translate("DialogPreferences", "Log transcoding commands and timestamps."))
        self.label_LogFile.setText(_translate("DialogPreferences", "Log File"))
        self.pushButton_BrowseLogFile.setText(_translate("DialogPreferences", "Browse"))
        self.pushButton_ClearLogFile.setText(_translate("DialogPreferences", "Clear Log"))
        self.groupBox_Options.setTitle(_translate("DialogPreferences", "Options"))
        self.checkBox_ChapterNameNumbers.setText(_translate("DialogPreferences", "Add numbers to chapter names."))
        self.checkBox_MP4StreamWarning.setText(_translate("DialogPreferences", "Warn if  .MP4 files have multiple audio streams."))
        self.checkBox_SetShortLastChapter.setText(_translate("DialogPreferences", "Set a short last chapter to this name when importing chapters:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_General), _translate("DialogPreferences", "General"))
        self.groupBox_FilenameTemplates.setTitle(_translate("DialogPreferences", "File Name Templates"))
        self.toolButton_FilenameTemplateAdd.setToolTip(_translate("DialogPreferences", "Add a file name template."))
        self.toolButton_FilenameTemplateAdd.setText(_translate("DialogPreferences", "..."))
        self.toolButton_FilenameTemplateCopy.setToolTip(_translate("DialogPreferences", "Copy the selected file name template."))
        self.toolButton_FilenameTemplateCopy.setText(_translate("DialogPreferences", "..."))
        self.toolButton_FilenameTemplateDelete.setToolTip(_translate("DialogPreferences", "Delete the selected file name template."))
        self.toolButton_FilenameTemplateDelete.setText(_translate("DialogPreferences", "..."))
        self.toolButton_FilenameTemplateMoveTop.setToolTip(_translate("DialogPreferences", "Move the selected file name template to the top of the list."))
        self.toolButton_FilenameTemplateMoveTop.setText(_translate("DialogPreferences", "..."))
        self.toolButton_FilenameTemplateUp.setToolTip(_translate("DialogPreferences", "Move the selected file name template up."))
        self.toolButton_FilenameTemplateUp.setText(_translate("DialogPreferences", "..."))
        self.toolButton_FilenameTemplateMoveDown.setToolTip(_translate("DialogPreferences", "Move the selected file name template down."))
        self.toolButton_FilenameTemplateMoveDown.setText(_translate("DialogPreferences", "..."))
        self.toolButton_FilenameTemplateMoveBottom.setToolTip(_translate("DialogPreferences", "Move the selected file name template to the bottom of the list."))
        self.toolButton_FilenameTemplateMoveBottom.setText(_translate("DialogPreferences", "..."))
        self.groupBox_FilenameCharacterReplacement.setTitle(_translate("DialogPreferences", "File Name Character Replacement"))
        self.checkBox_FilenameCharacterReplace.setText(_translate("DialogPreferences", "Replace characters in file name with"))
        self.label_FilenameCharacterToReplace.setText(_translate("DialogPreferences", "Characters to replace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Filename), _translate("DialogPreferences", "File Name"))
        self.toolButton_PresetAdd.setToolTip(_translate("DialogPreferences", "Add a file name template."))
        self.toolButton_PresetAdd.setText(_translate("DialogPreferences", "..."))
        self.toolButton_PresetCopy.setToolTip(_translate("DialogPreferences", "Copy the selected file name template."))
        self.toolButton_PresetCopy.setText(_translate("DialogPreferences", "..."))
        self.toolButton_PresetDelete.setToolTip(_translate("DialogPreferences", "Delete the selected file name template."))
        self.toolButton_PresetDelete.setText(_translate("DialogPreferences", "..."))
        self.toolButton_PresetMoveTop.setToolTip(_translate("DialogPreferences", "Move the selected file name template to the top of the list."))
        self.toolButton_PresetMoveTop.setText(_translate("DialogPreferences", "..."))
        self.toolButton_PresetUp.setToolTip(_translate("DialogPreferences", "Move the selected file name template up."))
        self.toolButton_PresetUp.setText(_translate("DialogPreferences", "..."))
        self.toolButton_PresetMoveDown.setToolTip(_translate("DialogPreferences", "Move the selected file name template down."))
        self.toolButton_PresetMoveDown.setText(_translate("DialogPreferences", "..."))
        self.toolButton_PresetMoveBottom.setToolTip(_translate("DialogPreferences", "Move the selected file name template to the bottom of the list."))
        self.toolButton_PresetMoveBottom.setText(_translate("DialogPreferences", "..."))
        self.groupBox_PresetDetails.setTitle(_translate("DialogPreferences", "Details"))
        self.label_PresetsTag.setText(_translate("DialogPreferences", "Tag"))
        self.label_PresetSettings.setText(_translate("DialogPreferences", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Presets), _translate("DialogPreferences", "Presets"))
        self.toolButton_MixdownAdd.setToolTip(_translate("DialogPreferences", "Add a file name template."))
        self.toolButton_MixdownAdd.setText(_translate("DialogPreferences", "..."))
        self.toolButton_MixdownCopy.setToolTip(_translate("DialogPreferences", "Copy the selected file name template."))
        self.toolButton_MixdownCopy.setText(_translate("DialogPreferences", "..."))
        self.toolButton_MixdownDelete.setToolTip(_translate("DialogPreferences", "Delete the selected file name template."))
        self.toolButton_MixdownDelete.setText(_translate("DialogPreferences", "..."))
        self.toolButton_MixdownMoveTop.setToolTip(_translate("DialogPreferences", "Move the selected file name template to the top of the list."))
        self.toolButton_MixdownMoveTop.setText(_translate("DialogPreferences", "..."))
        self.toolButton_MixdownUp.setToolTip(_translate("DialogPreferences", "Move the selected file name template up."))
        self.toolButton_MixdownUp.setText(_translate("DialogPreferences", "..."))
        self.toolButton_MixdownMoveDown.setToolTip(_translate("DialogPreferences", "Move the selected file name template down."))
        self.toolButton_MixdownMoveDown.setText(_translate("DialogPreferences", "..."))
        self.toolButton_MixdownMoveBottom.setToolTip(_translate("DialogPreferences", "Move the selected file name template to the bottom of the list."))
        self.toolButton_MixdownMoveBottom.setText(_translate("DialogPreferences", "..."))
        self.groupBox_MixdownDetails.setTitle(_translate("DialogPreferences", "Details"))
        self.label_MixdownTag.setText(_translate("DialogPreferences", "Tag"))
        self.label_MixdownEncoder.setText(_translate("DialogPreferences", "Encoder"))
        self.label_MixdownMixdown.setText(_translate("DialogPreferences", "Mixdown"))
        self.label_MixdownBitrate.setText(_translate("DialogPreferences", "Bitrate"))
        self.label_MixdownSampleRate.setText(_translate("DialogPreferences", "Sample Rate"))
        self.label_MixdonwDynamicRangeCompression.setText(_translate("DialogPreferences", "Dynamic Range Compression"))
        self.label_MixdownGain.setText(_translate("DialogPreferences", "Gain"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Mixdown), _translate("DialogPreferences", "Mixdown"))
        self.groupBox_DiscSessionAutomaticSessions.setTitle(_translate("DialogPreferences", "Automatic Sessions"))
        self.checkBox_DiscSessionsAutoDiscSessions.setText(_translate("DialogPreferences", "Use automatic disc sessions."))
        self.label_DiscSessionAutomaticSessionFolder.setText(_translate("DialogPreferences", "Automatic sessions folder"))
        self.pushButton_BrowseAutomaticSessionFolder.setText(_translate("DialogPreferences", "Browse"))
        self.label_DiscSessionAutomaticFilenamePrefix.setText(_translate("DialogPreferences", "Automatic file name prefix"))
        self.groupBoxDiscSessionLoadSession.setTitle(_translate("DialogPreferences", "Load Session"))
        self.checkBox_LoadSessionKeepPosition.setText(_translate("DialogPreferences", "On session load, keep the main window position."))
        self.checkBoxLoadSessionKeepSize.setText(_translate("DialogPreferences", "On session load, keep the main window size."))
        self.checkBoxLoadSessionKeepDestination.setText(_translate("DialogPreferences", "On session load, keep the destination. "))
        self.groupBox_NewSource.setTitle(_translate("DialogPreferences", "New Source"))
        self.checkBox_SelectFirstMask.setText(_translate("DialogPreferences", "Select the first file name mask."))
        self.checkBox_SelectFirstPreset.setText(_translate("DialogPreferences", "Select the first processing preset."))
        self.checkBox_DefaultDestination.setText(_translate("DialogPreferences", "Set default destination"))
        self.pushButton_BrowseDefaultDestination.setText(_translate("DialogPreferences", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DiscSession), _translate("DialogPreferences", "Disc Session"))
        self.groupBox_AutoTitles.setTitle(_translate("DialogPreferences", "Titles"))
        self.checkBox_AutoSelectLongestTitle.setText(_translate("DialogPreferences", "On new source, automatically select the longest title."))
        self.label_AutoShortTitleSeconds_1.setText(_translate("DialogPreferences", "Short titles are titles of"))
        self.label_AutoShortTitleSeconds_2.setText(_translate("DialogPreferences", "seconds or less."))
        self.groupBox_AutoAudioTracks.setTitle(_translate("DialogPreferences", "Audio Track(s)"))
        self.checkBox_AutoAudioPreferredLanguage.setText(_translate("DialogPreferences", "The preferred audio language is "))
        self.lineEdit_AutoAudioPreferredLanguage.setText(_translate("DialogPreferences", "eng"))
        self.checkBox_AutoAudioSelect51.setText(_translate("DialogPreferences", "Select the first 5.1 audio track (preferred language first)."))
        self.checkBox_AutoAudioSelectDTS.setText(_translate("DialogPreferences", "Select the first DTS or DTSHD audio track (preferred language first)."))
        self.checkBox_AutoAudioFallback.setText(_translate("DialogPreferences", "Fallback to the first available audio track (preferred language first)."))
        self.groupBox_AutoSubtitles.setTitle(_translate("DialogPreferences", "Subtitle(s)"))
        self.checkBox_AutoSubtitlePreferredLanguage.setText(_translate("DialogPreferences", "The preferred subtitle language is "))
        self.lineEdit_AutoSubtitlePreferredLanguage.setText(_translate("DialogPreferences", "eng"))
        self.checkBox_AutoSubtitleFirstTrack.setText(_translate("DialogPreferences", "Select the first subtitle track (preferred language first)."))
        self.checkBox_AutoSubtitleBurnIn.setText(_translate("DialogPreferences", "Burn-in the first selected subtitle."))
        self.checkBox_AutoSubtitleDefault.setText(_translate("DialogPreferences", "Make the first selected subtitle the default subtitle."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Auto1), _translate("DialogPreferences", "Auto"))
        self.groupBox_AutoAudioMixdowns.setTitle(_translate("DialogPreferences", "Audio Mixdown(s)"))
        self.label_AutoAudioMixdownPrimary.setText(_translate("DialogPreferences", "Primary"))
        self.label_AutoAudioMixdownSecondary.setText(_translate("DialogPreferences", "Secondary"))
        self.label_AutoAudioMidownAC3_51.setText(_translate("DialogPreferences", "AC3 5.1"))
        self.label_AutoAudioMixdownDTS.setText(_translate("DialogPreferences", "DTS"))
        self.label_AutoAudioMixdownDTSHD.setText(_translate("DialogPreferences", "DTSHD"))
        self.label_AutoAudioMixdownAC3.setText(_translate("DialogPreferences", "AC3"))
        self.label_AutoAudioMixdownDefault.setText(_translate("DialogPreferences", "Default"))
        self.groupBox_AutoCrop.setTitle(_translate("DialogPreferences", "Cropping"))
        self.checkBox_AutoCropReset.setText(_translate("DialogPreferences", "On new source, reset cropping from custom to automatic (if necessary)."))
        self.checkBox_AutoCropCopyLongestTitle.setText(_translate("DialogPreferences", "On new source, copy cropping information from longest title."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Auto2), _translate("DialogPreferences", "Auto"))

